// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/ligato/sfc-controller/plugins/k8scrd/pkg/apis/sfccontroller/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetworkNodeLister helps list NetworkNodes.
type NetworkNodeLister interface {
	// List lists all NetworkNodes in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.NetworkNode, err error)
	// NetworkNodes returns an object that can list and get NetworkNodes.
	NetworkNodes(namespace string) NetworkNodeNamespaceLister
	NetworkNodeListerExpansion
}

// networkNodeLister implements the NetworkNodeLister interface.
type networkNodeLister struct {
	indexer cache.Indexer
}

// NewNetworkNodeLister returns a new NetworkNodeLister.
func NewNetworkNodeLister(indexer cache.Indexer) NetworkNodeLister {
	return &networkNodeLister{indexer: indexer}
}

// List lists all NetworkNodes in the indexer.
func (s *networkNodeLister) List(selector labels.Selector) (ret []*v1alpha1.NetworkNode, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NetworkNode))
	})
	return ret, err
}

// NetworkNodes returns an object that can list and get NetworkNodes.
func (s *networkNodeLister) NetworkNodes(namespace string) NetworkNodeNamespaceLister {
	return networkNodeNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NetworkNodeNamespaceLister helps list and get NetworkNodes.
type NetworkNodeNamespaceLister interface {
	// List lists all NetworkNodes in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.NetworkNode, err error)
	// Get retrieves the NetworkNode from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.NetworkNode, error)
	NetworkNodeNamespaceListerExpansion
}

// networkNodeNamespaceLister implements the NetworkNodeNamespaceLister
// interface.
type networkNodeNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NetworkNodes in the indexer for a given namespace.
func (s networkNodeNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.NetworkNode, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NetworkNode))
	})
	return ret, err
}

// Get retrieves the NetworkNode from the indexer for a given namespace and name.
func (s networkNodeNamespaceLister) Get(name string) (*v1alpha1.NetworkNode, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("networknode"), name)
	}
	return obj.(*v1alpha1.NetworkNode), nil
}
