---
dist: trusty
sudo: required
language: go

go_import_path: github.com/ligato/sfc-controller

go:
  - 1.9.x

cache:
  directories:
    - $HOME/build-cache

before_install:
  - go get -u -f "github.com/alecthomas/gometalinter"
  - gometalinter --install
  - go get github.com/mattn/goveralls
  - sudo apt-get install npm && npm install -g markdown-link-check

script:
  - make yamllint
  - make check_links || true
  - make lint
  - make
  - make test-cover
  - make test-examples || true

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci
