// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	sfccontroller_v1alpha1 "github.com/ligato/sfc-controller/plugins/k8scrd/pkg/apis/sfccontroller/v1alpha1"
	versioned "github.com/ligato/sfc-controller/plugins/k8scrd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ligato/sfc-controller/plugins/k8scrd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ligato/sfc-controller/plugins/k8scrd/pkg/client/listers/sfccontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IpamPoolInformer provides access to a shared informer and lister for
// IpamPools.
type IpamPoolInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IpamPoolLister
}

type ipamPoolInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIpamPoolInformer constructs a new informer for IpamPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIpamPoolInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIpamPoolInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIpamPoolInformer constructs a new informer for IpamPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIpamPoolInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SfccontrollerV1alpha1().IpamPools(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SfccontrollerV1alpha1().IpamPools(namespace).Watch(options)
			},
		},
		&sfccontroller_v1alpha1.IpamPool{},
		resyncPeriod,
		indexers,
	)
}

func (f *ipamPoolInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIpamPoolInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ipamPoolInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sfccontroller_v1alpha1.IpamPool{}, f.defaultInformer)
}

func (f *ipamPoolInformer) Lister() v1alpha1.IpamPoolLister {
	return v1alpha1.NewIpamPoolLister(f.Informer().GetIndexer())
}
