// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: controller.proto

package controller

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type L3VRFRoute struct {
	VrfId                uint32   `protobuf:"varint,1,opt,name=vrf_id,json=vrfId,proto3" json:"vrf_id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DstIpAddr            string   `protobuf:"bytes,3,opt,name=dst_ip_addr,json=dstIpAddr,proto3" json:"dst_ip_addr,omitempty"`
	NextHopAddr          string   `protobuf:"bytes,4,opt,name=next_hop_addr,json=nextHopAddr,proto3" json:"next_hop_addr,omitempty"`
	OutgoingInterface    string   `protobuf:"bytes,5,opt,name=outgoing_interface,json=outgoingInterface,proto3" json:"outgoing_interface,omitempty"`
	Weight               uint32   `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Preference           uint32   `protobuf:"varint,7,opt,name=preference,proto3" json:"preference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L3VRFRoute) Reset()         { *m = L3VRFRoute{} }
func (m *L3VRFRoute) String() string { return proto.CompactTextString(m) }
func (*L3VRFRoute) ProtoMessage()    {}
func (*L3VRFRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{0}
}
func (m *L3VRFRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L3VRFRoute.Unmarshal(m, b)
}
func (m *L3VRFRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L3VRFRoute.Marshal(b, m, deterministic)
}
func (dst *L3VRFRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L3VRFRoute.Merge(dst, src)
}
func (m *L3VRFRoute) XXX_Size() int {
	return xxx_messageInfo_L3VRFRoute.Size(m)
}
func (m *L3VRFRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_L3VRFRoute.DiscardUnknown(m)
}

var xxx_messageInfo_L3VRFRoute proto.InternalMessageInfo

func (m *L3VRFRoute) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

func (m *L3VRFRoute) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *L3VRFRoute) GetDstIpAddr() string {
	if m != nil {
		return m.DstIpAddr
	}
	return ""
}

func (m *L3VRFRoute) GetNextHopAddr() string {
	if m != nil {
		return m.NextHopAddr
	}
	return ""
}

func (m *L3VRFRoute) GetOutgoingInterface() string {
	if m != nil {
		return m.OutgoingInterface
	}
	return ""
}

func (m *L3VRFRoute) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *L3VRFRoute) GetPreference() uint32 {
	if m != nil {
		return m.Preference
	}
	return 0
}

type L3ArpEntry struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	PhysAddress          string   `protobuf:"bytes,2,opt,name=phys_address,json=physAddress,proto3" json:"phys_address,omitempty"`
	OutgoingInterface    string   `protobuf:"bytes,3,opt,name=outgoing_interface,json=outgoingInterface,proto3" json:"outgoing_interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L3ArpEntry) Reset()         { *m = L3ArpEntry{} }
func (m *L3ArpEntry) String() string { return proto.CompactTextString(m) }
func (*L3ArpEntry) ProtoMessage()    {}
func (*L3ArpEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{1}
}
func (m *L3ArpEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L3ArpEntry.Unmarshal(m, b)
}
func (m *L3ArpEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L3ArpEntry.Marshal(b, m, deterministic)
}
func (dst *L3ArpEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L3ArpEntry.Merge(dst, src)
}
func (m *L3ArpEntry) XXX_Size() int {
	return xxx_messageInfo_L3ArpEntry.Size(m)
}
func (m *L3ArpEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_L3ArpEntry.DiscardUnknown(m)
}

var xxx_messageInfo_L3ArpEntry proto.InternalMessageInfo

func (m *L3ArpEntry) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *L3ArpEntry) GetPhysAddress() string {
	if m != nil {
		return m.PhysAddress
	}
	return ""
}

func (m *L3ArpEntry) GetOutgoingInterface() string {
	if m != nil {
		return m.OutgoingInterface
	}
	return ""
}

type L2FIBEntry struct {
	DestMacAddress       string   `protobuf:"bytes,1,opt,name=dest_mac_address,json=destMacAddress,proto3" json:"dest_mac_address,omitempty"`
	BdName               string   `protobuf:"bytes,2,opt,name=bd_name,json=bdName,proto3" json:"bd_name,omitempty"`
	OutgoingIf           string   `protobuf:"bytes,3,opt,name=outgoing_if,json=outgoingIf,proto3" json:"outgoing_if,omitempty"`
	Action               string   `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Bvi                  bool     `protobuf:"varint,5,opt,name=bvi,proto3" json:"bvi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2FIBEntry) Reset()         { *m = L2FIBEntry{} }
func (m *L2FIBEntry) String() string { return proto.CompactTextString(m) }
func (*L2FIBEntry) ProtoMessage()    {}
func (*L2FIBEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{2}
}
func (m *L2FIBEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2FIBEntry.Unmarshal(m, b)
}
func (m *L2FIBEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2FIBEntry.Marshal(b, m, deterministic)
}
func (dst *L2FIBEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2FIBEntry.Merge(dst, src)
}
func (m *L2FIBEntry) XXX_Size() int {
	return xxx_messageInfo_L2FIBEntry.Size(m)
}
func (m *L2FIBEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_L2FIBEntry.DiscardUnknown(m)
}

var xxx_messageInfo_L2FIBEntry proto.InternalMessageInfo

func (m *L2FIBEntry) GetDestMacAddress() string {
	if m != nil {
		return m.DestMacAddress
	}
	return ""
}

func (m *L2FIBEntry) GetBdName() string {
	if m != nil {
		return m.BdName
	}
	return ""
}

func (m *L2FIBEntry) GetOutgoingIf() string {
	if m != nil {
		return m.OutgoingIf
	}
	return ""
}

func (m *L2FIBEntry) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *L2FIBEntry) GetBvi() bool {
	if m != nil {
		return m.Bvi
	}
	return false
}

type BDParms struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Flood                bool     `protobuf:"varint,2,opt,name=flood,proto3" json:"flood,omitempty"`
	UnknownUnicastFlood  bool     `protobuf:"varint,3,opt,name=unknown_unicast_flood,json=unknownUnicastFlood,proto3" json:"unknown_unicast_flood,omitempty"`
	Forward              bool     `protobuf:"varint,4,opt,name=forward,proto3" json:"forward,omitempty"`
	Learn                bool     `protobuf:"varint,5,opt,name=learn,proto3" json:"learn,omitempty"`
	ArpTermination       bool     `protobuf:"varint,6,opt,name=arp_termination,json=arpTermination,proto3" json:"arp_termination,omitempty"`
	MacAgeMinutes        uint32   `protobuf:"varint,7,opt,name=mac_age_minutes,json=macAgeMinutes,proto3" json:"mac_age_minutes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BDParms) Reset()         { *m = BDParms{} }
func (m *BDParms) String() string { return proto.CompactTextString(m) }
func (*BDParms) ProtoMessage()    {}
func (*BDParms) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{3}
}
func (m *BDParms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BDParms.Unmarshal(m, b)
}
func (m *BDParms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BDParms.Marshal(b, m, deterministic)
}
func (dst *BDParms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BDParms.Merge(dst, src)
}
func (m *BDParms) XXX_Size() int {
	return xxx_messageInfo_BDParms.Size(m)
}
func (m *BDParms) XXX_DiscardUnknown() {
	xxx_messageInfo_BDParms.DiscardUnknown(m)
}

var xxx_messageInfo_BDParms proto.InternalMessageInfo

func (m *BDParms) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BDParms) GetFlood() bool {
	if m != nil {
		return m.Flood
	}
	return false
}

func (m *BDParms) GetUnknownUnicastFlood() bool {
	if m != nil {
		return m.UnknownUnicastFlood
	}
	return false
}

func (m *BDParms) GetForward() bool {
	if m != nil {
		return m.Forward
	}
	return false
}

func (m *BDParms) GetLearn() bool {
	if m != nil {
		return m.Learn
	}
	return false
}

func (m *BDParms) GetArpTermination() bool {
	if m != nil {
		return m.ArpTermination
	}
	return false
}

func (m *BDParms) GetMacAgeMinutes() uint32 {
	if m != nil {
		return m.MacAgeMinutes
	}
	return 0
}

type L2BD struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BdParms              *BDParms `protobuf:"bytes,2,opt,name=bd_parms,json=bdParms,proto3" json:"bd_parms,omitempty"`
	L2BdTemplate         string   `protobuf:"bytes,3,opt,name=l2bd_template,json=l2bdTemplate,proto3" json:"l2bd_template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2BD) Reset()         { *m = L2BD{} }
func (m *L2BD) String() string { return proto.CompactTextString(m) }
func (*L2BD) ProtoMessage()    {}
func (*L2BD) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{4}
}
func (m *L2BD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2BD.Unmarshal(m, b)
}
func (m *L2BD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2BD.Marshal(b, m, deterministic)
}
func (dst *L2BD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2BD.Merge(dst, src)
}
func (m *L2BD) XXX_Size() int {
	return xxx_messageInfo_L2BD.Size(m)
}
func (m *L2BD) XXX_DiscardUnknown() {
	xxx_messageInfo_L2BD.DiscardUnknown(m)
}

var xxx_messageInfo_L2BD proto.InternalMessageInfo

func (m *L2BD) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *L2BD) GetBdParms() *BDParms {
	if m != nil {
		return m.BdParms
	}
	return nil
}

func (m *L2BD) GetL2BdTemplate() string {
	if m != nil {
		return m.L2BdTemplate
	}
	return ""
}

// IPAM will choose an address using the prefix.  In the example, there is an 8 bit address space [0..255]
// if 0..255 are not desired then a start and end address can be used.  See comments below.
type IPAMPoolStatus struct {
	Addresses            map[string]string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *IPAMPoolStatus) Reset()         { *m = IPAMPoolStatus{} }
func (m *IPAMPoolStatus) String() string { return proto.CompactTextString(m) }
func (*IPAMPoolStatus) ProtoMessage()    {}
func (*IPAMPoolStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{5}
}
func (m *IPAMPoolStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPAMPoolStatus.Unmarshal(m, b)
}
func (m *IPAMPoolStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPAMPoolStatus.Marshal(b, m, deterministic)
}
func (dst *IPAMPoolStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPAMPoolStatus.Merge(dst, src)
}
func (m *IPAMPoolStatus) XXX_Size() int {
	return xxx_messageInfo_IPAMPoolStatus.Size(m)
}
func (m *IPAMPoolStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_IPAMPoolStatus.DiscardUnknown(m)
}

var xxx_messageInfo_IPAMPoolStatus proto.InternalMessageInfo

func (m *IPAMPoolStatus) GetAddresses() map[string]string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type IPAMPoolSpec struct {
	Scope                string   `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Network              string   `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	StartRange           uint32   `protobuf:"varint,4,opt,name=start_range,json=startRange,proto3" json:"start_range,omitempty"`
	EndRange             uint32   `protobuf:"varint,5,opt,name=end_range,json=endRange,proto3" json:"end_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPAMPoolSpec) Reset()         { *m = IPAMPoolSpec{} }
func (m *IPAMPoolSpec) String() string { return proto.CompactTextString(m) }
func (*IPAMPoolSpec) ProtoMessage()    {}
func (*IPAMPoolSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{6}
}
func (m *IPAMPoolSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPAMPoolSpec.Unmarshal(m, b)
}
func (m *IPAMPoolSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPAMPoolSpec.Marshal(b, m, deterministic)
}
func (dst *IPAMPoolSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPAMPoolSpec.Merge(dst, src)
}
func (m *IPAMPoolSpec) XXX_Size() int {
	return xxx_messageInfo_IPAMPoolSpec.Size(m)
}
func (m *IPAMPoolSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_IPAMPoolSpec.DiscardUnknown(m)
}

var xxx_messageInfo_IPAMPoolSpec proto.InternalMessageInfo

func (m *IPAMPoolSpec) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *IPAMPoolSpec) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *IPAMPoolSpec) GetStartRange() uint32 {
	if m != nil {
		return m.StartRange
	}
	return 0
}

func (m *IPAMPoolSpec) GetEndRange() uint32 {
	if m != nil {
		return m.EndRange
	}
	return 0
}

type IPAMPool struct {
	Metadata             *MetaDataType   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *IPAMPoolSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *IPAMPoolStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IPAMPool) Reset()         { *m = IPAMPool{} }
func (m *IPAMPool) String() string { return proto.CompactTextString(m) }
func (*IPAMPool) ProtoMessage()    {}
func (*IPAMPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{7}
}
func (m *IPAMPool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPAMPool.Unmarshal(m, b)
}
func (m *IPAMPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPAMPool.Marshal(b, m, deterministic)
}
func (dst *IPAMPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPAMPool.Merge(dst, src)
}
func (m *IPAMPool) XXX_Size() int {
	return xxx_messageInfo_IPAMPool.Size(m)
}
func (m *IPAMPool) XXX_DiscardUnknown() {
	xxx_messageInfo_IPAMPool.DiscardUnknown(m)
}

var xxx_messageInfo_IPAMPool proto.InternalMessageInfo

func (m *IPAMPool) GetMetadata() *MetaDataType {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *IPAMPool) GetSpec() *IPAMPoolSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *IPAMPool) GetStatus() *IPAMPoolStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type SystemParameters struct {
	Mtu                          uint32     `protobuf:"varint,1,opt,name=mtu,proto3" json:"mtu,omitempty"`
	MemifDirectory               string     `protobuf:"bytes,2,opt,name=memif_directory,json=memifDirectory,proto3" json:"memif_directory,omitempty"`
	DefaultStaticRouteWeight     uint32     `protobuf:"varint,3,opt,name=default_static_route_weight,json=defaultStaticRouteWeight,proto3" json:"default_static_route_weight,omitempty"`
	DefaultStaticRoutePreference uint32     `protobuf:"varint,4,opt,name=default_static_route_preference,json=defaultStaticRoutePreference,proto3" json:"default_static_route_preference,omitempty"`
	L2BdTemplates                []*BDParms `protobuf:"bytes,5,rep,name=l2bd_templates,json=l2bdTemplates,proto3" json:"l2bd_templates,omitempty"`
	RxMode                       string     `protobuf:"bytes,7,opt,name=rx_mode,json=rxMode,proto3" json:"rx_mode,omitempty"`
	MinVrfId                     uint32     `protobuf:"varint,8,opt,name=min_vrf_id,json=minVrfId,proto3" json:"min_vrf_id,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}   `json:"-"`
	XXX_unrecognized             []byte     `json:"-"`
	XXX_sizecache                int32      `json:"-"`
}

func (m *SystemParameters) Reset()         { *m = SystemParameters{} }
func (m *SystemParameters) String() string { return proto.CompactTextString(m) }
func (*SystemParameters) ProtoMessage()    {}
func (*SystemParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{8}
}
func (m *SystemParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemParameters.Unmarshal(m, b)
}
func (m *SystemParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemParameters.Marshal(b, m, deterministic)
}
func (dst *SystemParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemParameters.Merge(dst, src)
}
func (m *SystemParameters) XXX_Size() int {
	return xxx_messageInfo_SystemParameters.Size(m)
}
func (m *SystemParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemParameters.DiscardUnknown(m)
}

var xxx_messageInfo_SystemParameters proto.InternalMessageInfo

func (m *SystemParameters) GetMtu() uint32 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *SystemParameters) GetMemifDirectory() string {
	if m != nil {
		return m.MemifDirectory
	}
	return ""
}

func (m *SystemParameters) GetDefaultStaticRouteWeight() uint32 {
	if m != nil {
		return m.DefaultStaticRouteWeight
	}
	return 0
}

func (m *SystemParameters) GetDefaultStaticRoutePreference() uint32 {
	if m != nil {
		return m.DefaultStaticRoutePreference
	}
	return 0
}

func (m *SystemParameters) GetL2BdTemplates() []*BDParms {
	if m != nil {
		return m.L2BdTemplates
	}
	return nil
}

func (m *SystemParameters) GetRxMode() string {
	if m != nil {
		return m.RxMode
	}
	return ""
}

func (m *SystemParameters) GetMinVrfId() uint32 {
	if m != nil {
		return m.MinVrfId
	}
	return 0
}

type NetworkPodToNodeMap struct {
	Pod                  string   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Node                 string   `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkPodToNodeMap) Reset()         { *m = NetworkPodToNodeMap{} }
func (m *NetworkPodToNodeMap) String() string { return proto.CompactTextString(m) }
func (*NetworkPodToNodeMap) ProtoMessage()    {}
func (*NetworkPodToNodeMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{9}
}
func (m *NetworkPodToNodeMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPodToNodeMap.Unmarshal(m, b)
}
func (m *NetworkPodToNodeMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPodToNodeMap.Marshal(b, m, deterministic)
}
func (dst *NetworkPodToNodeMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPodToNodeMap.Merge(dst, src)
}
func (m *NetworkPodToNodeMap) XXX_Size() int {
	return xxx_messageInfo_NetworkPodToNodeMap.Size(m)
}
func (m *NetworkPodToNodeMap) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPodToNodeMap.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPodToNodeMap proto.InternalMessageInfo

func (m *NetworkPodToNodeMap) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

func (m *NetworkPodToNodeMap) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

// The rendered vpp agent entry is identified by the key, and type, which are used
// to read the entry from etcd
type RenderedVppAgentEntry struct {
	VppAgentKey          string   `protobuf:"bytes,1,opt,name=vpp_agent_key,json=vppAgentKey,proto3" json:"vpp_agent_key,omitempty"`
	VppAgentType         string   `protobuf:"bytes,2,opt,name=vpp_agent_type,json=vppAgentType,proto3" json:"vpp_agent_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderedVppAgentEntry) Reset()         { *m = RenderedVppAgentEntry{} }
func (m *RenderedVppAgentEntry) String() string { return proto.CompactTextString(m) }
func (*RenderedVppAgentEntry) ProtoMessage()    {}
func (*RenderedVppAgentEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{10}
}
func (m *RenderedVppAgentEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderedVppAgentEntry.Unmarshal(m, b)
}
func (m *RenderedVppAgentEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderedVppAgentEntry.Marshal(b, m, deterministic)
}
func (dst *RenderedVppAgentEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderedVppAgentEntry.Merge(dst, src)
}
func (m *RenderedVppAgentEntry) XXX_Size() int {
	return xxx_messageInfo_RenderedVppAgentEntry.Size(m)
}
func (m *RenderedVppAgentEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderedVppAgentEntry.DiscardUnknown(m)
}

var xxx_messageInfo_RenderedVppAgentEntry proto.InternalMessageInfo

func (m *RenderedVppAgentEntry) GetVppAgentKey() string {
	if m != nil {
		return m.VppAgentKey
	}
	return ""
}

func (m *RenderedVppAgentEntry) GetVppAgentType() string {
	if m != nil {
		return m.VppAgentType
	}
	return ""
}

//
// Interface
//
type InterfaceStatus struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               string            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  []string          `protobuf:"bytes,3,rep,name=msg,proto3" json:"msg,omitempty"`
	MacAddress           string            `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	MacAddrID            uint32            `protobuf:"varint,5,opt,name=macAddrID,proto3" json:"macAddrID,omitempty"`
	IpamPoolNums         map[string]uint32 `protobuf:"bytes,6,rep,name=ipam_pool_nums,json=ipamPoolNums,proto3" json:"ipam_pool_nums,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	IpAddresses          []string          `protobuf:"bytes,7,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	MemifID              uint32            `protobuf:"varint,8,opt,name=memifID,proto3" json:"memifID,omitempty"`
	Node                 string            `protobuf:"bytes,10,opt,name=node,proto3" json:"node,omitempty"`
	HostPortLabel        string            `protobuf:"bytes,11,opt,name=host_port_label,json=hostPortLabel,proto3" json:"host_port_label,omitempty"`
	Vni                  uint32            `protobuf:"varint,12,opt,name=vni,proto3" json:"vni,omitempty"`
	NnoName              string            `protobuf:"bytes,13,opt,name=nno_name,json=nnoName,proto3" json:"nno_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InterfaceStatus) Reset()         { *m = InterfaceStatus{} }
func (m *InterfaceStatus) String() string { return proto.CompactTextString(m) }
func (*InterfaceStatus) ProtoMessage()    {}
func (*InterfaceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{11}
}
func (m *InterfaceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceStatus.Unmarshal(m, b)
}
func (m *InterfaceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceStatus.Marshal(b, m, deterministic)
}
func (dst *InterfaceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceStatus.Merge(dst, src)
}
func (m *InterfaceStatus) XXX_Size() int {
	return xxx_messageInfo_InterfaceStatus.Size(m)
}
func (m *InterfaceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceStatus proto.InternalMessageInfo

func (m *InterfaceStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InterfaceStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *InterfaceStatus) GetMsg() []string {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *InterfaceStatus) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *InterfaceStatus) GetMacAddrID() uint32 {
	if m != nil {
		return m.MacAddrID
	}
	return 0
}

func (m *InterfaceStatus) GetIpamPoolNums() map[string]uint32 {
	if m != nil {
		return m.IpamPoolNums
	}
	return nil
}

func (m *InterfaceStatus) GetIpAddresses() []string {
	if m != nil {
		return m.IpAddresses
	}
	return nil
}

func (m *InterfaceStatus) GetMemifID() uint32 {
	if m != nil {
		return m.MemifID
	}
	return 0
}

func (m *InterfaceStatus) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *InterfaceStatus) GetHostPortLabel() string {
	if m != nil {
		return m.HostPortLabel
	}
	return ""
}

func (m *InterfaceStatus) GetVni() uint32 {
	if m != nil {
		return m.Vni
	}
	return 0
}

func (m *InterfaceStatus) GetNnoName() string {
	if m != nil {
		return m.NnoName
	}
	return ""
}

type Interface struct {
	Name           string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BypassRenderer bool   `protobuf:"varint,2,opt,name=bypass_renderer,json=bypassRenderer,proto3" json:"bypass_renderer,omitempty"`
	IfType         string `protobuf:"bytes,3,opt,name=if_type,json=ifType,proto3" json:"if_type,omitempty"`
	MacAddress     string `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// 02:00:00:00:00:00 as base, last octet increments
	Mtu                  uint32                         `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	RxMode               string                         `protobuf:"bytes,6,opt,name=rx_mode,json=rxMode,proto3" json:"rx_mode,omitempty"`
	IpAddresses          []string                       `protobuf:"bytes,7,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	IpamPoolNames        []string                       `protobuf:"bytes,9,rep,name=ipam_pool_names,json=ipamPoolNames,proto3" json:"ipam_pool_names,omitempty"`
	AdminStatus          string                         `protobuf:"bytes,10,opt,name=admin_status,json=adminStatus,proto3" json:"admin_status,omitempty"`
	MemifParms           *Interface_MemIFParms          `protobuf:"bytes,11,opt,name=memif_parms,json=memifParms,proto3" json:"memif_parms,omitempty"`
	TapParms             *Interface_TapParms            `protobuf:"bytes,12,opt,name=tap_parms,json=tapParms,proto3" json:"tap_parms,omitempty"`
	Labels               []string                       `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty"`
	Parent               string                         `protobuf:"bytes,14,opt,name=parent,proto3" json:"parent,omitempty"`
	HostPortLabel        string                         `protobuf:"bytes,15,opt,name=host_port_label,json=hostPortLabel,proto3" json:"host_port_label,omitempty"`
	Fwd                  *Interface_Forwarding          `protobuf:"bytes,16,opt,name=fwd,proto3" json:"fwd,omitempty"`
	LinuxNamespace       *Interface_LinuxNamespace      `protobuf:"bytes,17,opt,name=linux_namespace,json=linuxNamespace,proto3" json:"linux_namespace,omitempty"`
	RxPlacementSettings  *Interface_RxPlacementSettings `protobuf:"bytes,18,opt,name=rx_placement_settings,json=rxPlacementSettings,proto3" json:"rx_placement_settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Interface) Reset()         { *m = Interface{} }
func (m *Interface) String() string { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()    {}
func (*Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{12}
}
func (m *Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface.Unmarshal(m, b)
}
func (m *Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface.Marshal(b, m, deterministic)
}
func (dst *Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface.Merge(dst, src)
}
func (m *Interface) XXX_Size() int {
	return xxx_messageInfo_Interface.Size(m)
}
func (m *Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Interface proto.InternalMessageInfo

func (m *Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interface) GetBypassRenderer() bool {
	if m != nil {
		return m.BypassRenderer
	}
	return false
}

func (m *Interface) GetIfType() string {
	if m != nil {
		return m.IfType
	}
	return ""
}

func (m *Interface) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *Interface) GetMtu() uint32 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *Interface) GetRxMode() string {
	if m != nil {
		return m.RxMode
	}
	return ""
}

func (m *Interface) GetIpAddresses() []string {
	if m != nil {
		return m.IpAddresses
	}
	return nil
}

func (m *Interface) GetIpamPoolNames() []string {
	if m != nil {
		return m.IpamPoolNames
	}
	return nil
}

func (m *Interface) GetAdminStatus() string {
	if m != nil {
		return m.AdminStatus
	}
	return ""
}

func (m *Interface) GetMemifParms() *Interface_MemIFParms {
	if m != nil {
		return m.MemifParms
	}
	return nil
}

func (m *Interface) GetTapParms() *Interface_TapParms {
	if m != nil {
		return m.TapParms
	}
	return nil
}

func (m *Interface) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Interface) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Interface) GetHostPortLabel() string {
	if m != nil {
		return m.HostPortLabel
	}
	return ""
}

func (m *Interface) GetFwd() *Interface_Forwarding {
	if m != nil {
		return m.Fwd
	}
	return nil
}

func (m *Interface) GetLinuxNamespace() *Interface_LinuxNamespace {
	if m != nil {
		return m.LinuxNamespace
	}
	return nil
}

func (m *Interface) GetRxPlacementSettings() *Interface_RxPlacementSettings {
	if m != nil {
		return m.RxPlacementSettings
	}
	return nil
}

type Interface_MemIFParms struct {
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	MemifDirectory       string   `protobuf:"bytes,2,opt,name=memif_directory,json=memifDirectory,proto3" json:"memif_directory,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	RingSize             string   `protobuf:"bytes,4,opt,name=ring_size,json=ringSize,proto3" json:"ring_size,omitempty"`
	BufferSize           string   `protobuf:"bytes,5,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	RxQueues             string   `protobuf:"bytes,6,opt,name=rx_queues,json=rxQueues,proto3" json:"rx_queues,omitempty"`
	TxQueues             string   `protobuf:"bytes,7,opt,name=tx_queues,json=txQueues,proto3" json:"tx_queues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interface_MemIFParms) Reset()         { *m = Interface_MemIFParms{} }
func (m *Interface_MemIFParms) String() string { return proto.CompactTextString(m) }
func (*Interface_MemIFParms) ProtoMessage()    {}
func (*Interface_MemIFParms) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{12, 0}
}
func (m *Interface_MemIFParms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface_MemIFParms.Unmarshal(m, b)
}
func (m *Interface_MemIFParms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface_MemIFParms.Marshal(b, m, deterministic)
}
func (dst *Interface_MemIFParms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface_MemIFParms.Merge(dst, src)
}
func (m *Interface_MemIFParms) XXX_Size() int {
	return xxx_messageInfo_Interface_MemIFParms.Size(m)
}
func (m *Interface_MemIFParms) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface_MemIFParms.DiscardUnknown(m)
}

var xxx_messageInfo_Interface_MemIFParms proto.InternalMessageInfo

func (m *Interface_MemIFParms) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *Interface_MemIFParms) GetMemifDirectory() string {
	if m != nil {
		return m.MemifDirectory
	}
	return ""
}

func (m *Interface_MemIFParms) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Interface_MemIFParms) GetRingSize() string {
	if m != nil {
		return m.RingSize
	}
	return ""
}

func (m *Interface_MemIFParms) GetBufferSize() string {
	if m != nil {
		return m.BufferSize
	}
	return ""
}

func (m *Interface_MemIFParms) GetRxQueues() string {
	if m != nil {
		return m.RxQueues
	}
	return ""
}

func (m *Interface_MemIFParms) GetTxQueues() string {
	if m != nil {
		return m.TxQueues
	}
	return ""
}

type Interface_TapParms struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RxRingSize           string   `protobuf:"bytes,2,opt,name=rx_ring_size,json=rxRingSize,proto3" json:"rx_ring_size,omitempty"`
	TxRingSize           string   `protobuf:"bytes,3,opt,name=tx_ring_size,json=txRingSize,proto3" json:"tx_ring_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interface_TapParms) Reset()         { *m = Interface_TapParms{} }
func (m *Interface_TapParms) String() string { return proto.CompactTextString(m) }
func (*Interface_TapParms) ProtoMessage()    {}
func (*Interface_TapParms) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{12, 1}
}
func (m *Interface_TapParms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface_TapParms.Unmarshal(m, b)
}
func (m *Interface_TapParms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface_TapParms.Marshal(b, m, deterministic)
}
func (dst *Interface_TapParms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface_TapParms.Merge(dst, src)
}
func (m *Interface_TapParms) XXX_Size() int {
	return xxx_messageInfo_Interface_TapParms.Size(m)
}
func (m *Interface_TapParms) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface_TapParms.DiscardUnknown(m)
}

var xxx_messageInfo_Interface_TapParms proto.InternalMessageInfo

func (m *Interface_TapParms) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Interface_TapParms) GetRxRingSize() string {
	if m != nil {
		return m.RxRingSize
	}
	return ""
}

func (m *Interface_TapParms) GetTxRingSize() string {
	if m != nil {
		return m.TxRingSize
	}
	return ""
}

type Interface_Forwarding struct {
	L3VrfRoute           []*L3VRFRoute `protobuf:"bytes,1,rep,name=l3_vrf_route,json=l3VrfRoute,proto3" json:"l3_vrf_route,omitempty"`
	L3Arp                []*L3ArpEntry `protobuf:"bytes,2,rep,name=l3_arp,json=l3Arp,proto3" json:"l3_arp,omitempty"`
	L2Fib                []*L2FIBEntry `protobuf:"bytes,3,rep,name=l2_fib,json=l2Fib,proto3" json:"l2_fib,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Interface_Forwarding) Reset()         { *m = Interface_Forwarding{} }
func (m *Interface_Forwarding) String() string { return proto.CompactTextString(m) }
func (*Interface_Forwarding) ProtoMessage()    {}
func (*Interface_Forwarding) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{12, 2}
}
func (m *Interface_Forwarding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface_Forwarding.Unmarshal(m, b)
}
func (m *Interface_Forwarding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface_Forwarding.Marshal(b, m, deterministic)
}
func (dst *Interface_Forwarding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface_Forwarding.Merge(dst, src)
}
func (m *Interface_Forwarding) XXX_Size() int {
	return xxx_messageInfo_Interface_Forwarding.Size(m)
}
func (m *Interface_Forwarding) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface_Forwarding.DiscardUnknown(m)
}

var xxx_messageInfo_Interface_Forwarding proto.InternalMessageInfo

func (m *Interface_Forwarding) GetL3VrfRoute() []*L3VRFRoute {
	if m != nil {
		return m.L3VrfRoute
	}
	return nil
}

func (m *Interface_Forwarding) GetL3Arp() []*L3ArpEntry {
	if m != nil {
		return m.L3Arp
	}
	return nil
}

func (m *Interface_Forwarding) GetL2Fib() []*L2FIBEntry {
	if m != nil {
		return m.L2Fib
	}
	return nil
}

type Interface_LinuxNamespace struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Pid                  uint32   `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Microservice         string   `protobuf:"bytes,3,opt,name=microservice,proto3" json:"microservice,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Filepath             string   `protobuf:"bytes,5,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interface_LinuxNamespace) Reset()         { *m = Interface_LinuxNamespace{} }
func (m *Interface_LinuxNamespace) String() string { return proto.CompactTextString(m) }
func (*Interface_LinuxNamespace) ProtoMessage()    {}
func (*Interface_LinuxNamespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{12, 3}
}
func (m *Interface_LinuxNamespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface_LinuxNamespace.Unmarshal(m, b)
}
func (m *Interface_LinuxNamespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface_LinuxNamespace.Marshal(b, m, deterministic)
}
func (dst *Interface_LinuxNamespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface_LinuxNamespace.Merge(dst, src)
}
func (m *Interface_LinuxNamespace) XXX_Size() int {
	return xxx_messageInfo_Interface_LinuxNamespace.Size(m)
}
func (m *Interface_LinuxNamespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface_LinuxNamespace.DiscardUnknown(m)
}

var xxx_messageInfo_Interface_LinuxNamespace proto.InternalMessageInfo

func (m *Interface_LinuxNamespace) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Interface_LinuxNamespace) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Interface_LinuxNamespace) GetMicroservice() string {
	if m != nil {
		return m.Microservice
	}
	return ""
}

func (m *Interface_LinuxNamespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interface_LinuxNamespace) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

type Interface_RxPlacementSettings struct {
	Queue                uint32   `protobuf:"varint,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Worker               uint32   `protobuf:"varint,2,opt,name=worker,proto3" json:"worker,omitempty"`
	IsMain               bool     `protobuf:"varint,3,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interface_RxPlacementSettings) Reset()         { *m = Interface_RxPlacementSettings{} }
func (m *Interface_RxPlacementSettings) String() string { return proto.CompactTextString(m) }
func (*Interface_RxPlacementSettings) ProtoMessage()    {}
func (*Interface_RxPlacementSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{12, 4}
}
func (m *Interface_RxPlacementSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface_RxPlacementSettings.Unmarshal(m, b)
}
func (m *Interface_RxPlacementSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface_RxPlacementSettings.Marshal(b, m, deterministic)
}
func (dst *Interface_RxPlacementSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface_RxPlacementSettings.Merge(dst, src)
}
func (m *Interface_RxPlacementSettings) XXX_Size() int {
	return xxx_messageInfo_Interface_RxPlacementSettings.Size(m)
}
func (m *Interface_RxPlacementSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface_RxPlacementSettings.DiscardUnknown(m)
}

var xxx_messageInfo_Interface_RxPlacementSettings proto.InternalMessageInfo

func (m *Interface_RxPlacementSettings) GetQueue() uint32 {
	if m != nil {
		return m.Queue
	}
	return 0
}

func (m *Interface_RxPlacementSettings) GetWorker() uint32 {
	if m != nil {
		return m.Worker
	}
	return 0
}

func (m *Interface_RxPlacementSettings) GetIsMain() bool {
	if m != nil {
		return m.IsMain
	}
	return false
}

type NetworkPodSpec struct {
	PodType              string       `protobuf:"bytes,2,opt,name=pod_type,json=podType,proto3" json:"pod_type,omitempty"`
	Interfaces           []*Interface `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	L2Bds                []*L2BD      `protobuf:"bytes,4,rep,name=l2bds,proto3" json:"l2bds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NetworkPodSpec) Reset()         { *m = NetworkPodSpec{} }
func (m *NetworkPodSpec) String() string { return proto.CompactTextString(m) }
func (*NetworkPodSpec) ProtoMessage()    {}
func (*NetworkPodSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{13}
}
func (m *NetworkPodSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPodSpec.Unmarshal(m, b)
}
func (m *NetworkPodSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPodSpec.Marshal(b, m, deterministic)
}
func (dst *NetworkPodSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPodSpec.Merge(dst, src)
}
func (m *NetworkPodSpec) XXX_Size() int {
	return xxx_messageInfo_NetworkPodSpec.Size(m)
}
func (m *NetworkPodSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPodSpec.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPodSpec proto.InternalMessageInfo

func (m *NetworkPodSpec) GetPodType() string {
	if m != nil {
		return m.PodType
	}
	return ""
}

func (m *NetworkPodSpec) GetInterfaces() []*Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *NetworkPodSpec) GetL2Bds() []*L2BD {
	if m != nil {
		return m.L2Bds
	}
	return nil
}

type NetworkPod struct {
	Metadata             *MetaDataType   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *NetworkPodSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NetworkPod) Reset()         { *m = NetworkPod{} }
func (m *NetworkPod) String() string { return proto.CompactTextString(m) }
func (*NetworkPod) ProtoMessage()    {}
func (*NetworkPod) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{14}
}
func (m *NetworkPod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPod.Unmarshal(m, b)
}
func (m *NetworkPod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPod.Marshal(b, m, deterministic)
}
func (dst *NetworkPod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPod.Merge(dst, src)
}
func (m *NetworkPod) XXX_Size() int {
	return xxx_messageInfo_NetworkPod.Size(m)
}
func (m *NetworkPod) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPod.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPod proto.InternalMessageInfo

func (m *NetworkPod) GetMetadata() *MetaDataType {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NetworkPod) GetSpec() *NetworkPodSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type Connection struct {
	Name                   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ConnType               string   `protobuf:"bytes,2,opt,name=conn_type,json=connType,proto3" json:"conn_type,omitempty"`
	NetworkNodeOverlayName string   `protobuf:"bytes,3,opt,name=network_node_overlay_name,json=networkNodeOverlayName,proto3" json:"network_node_overlay_name,omitempty"`
	PodInterfaces          []string `protobuf:"bytes,4,rep,name=pod_interfaces,json=podInterfaces,proto3" json:"pod_interfaces,omitempty"`
	NodeInterfaces         []string `protobuf:"bytes,5,rep,name=node_interfaces,json=nodeInterfaces,proto3" json:"node_interfaces,omitempty"`
	NodeInterfaceLabels    []string `protobuf:"bytes,6,rep,name=node_interface_labels,json=nodeInterfaceLabels,proto3" json:"node_interface_labels,omitempty"`
	UseNodeL2Bd            string   `protobuf:"bytes,7,opt,name=use_node_l2bd,json=useNodeL2bd,proto3" json:"use_node_l2bd,omitempty"`
	// only for l2mp connections
	L2Bd *L2BD `protobuf:"bytes,8,opt,name=l2bd,proto3" json:"l2bd,omitempty"`
	// create a l2bd with default parms for l2mp connections
	VrfId                uint32   `protobuf:"varint,9,opt,name=vrf_id,json=vrfId,proto3" json:"vrf_id,omitempty"`
	ConnMethod           string   `protobuf:"bytes,10,opt,name=conn_method,json=connMethod,proto3" json:"conn_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{15}
}
func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (dst *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(dst, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Connection) GetConnType() string {
	if m != nil {
		return m.ConnType
	}
	return ""
}

func (m *Connection) GetNetworkNodeOverlayName() string {
	if m != nil {
		return m.NetworkNodeOverlayName
	}
	return ""
}

func (m *Connection) GetPodInterfaces() []string {
	if m != nil {
		return m.PodInterfaces
	}
	return nil
}

func (m *Connection) GetNodeInterfaces() []string {
	if m != nil {
		return m.NodeInterfaces
	}
	return nil
}

func (m *Connection) GetNodeInterfaceLabels() []string {
	if m != nil {
		return m.NodeInterfaceLabels
	}
	return nil
}

func (m *Connection) GetUseNodeL2Bd() string {
	if m != nil {
		return m.UseNodeL2Bd
	}
	return ""
}

func (m *Connection) GetL2Bd() *L2BD {
	if m != nil {
		return m.L2Bd
	}
	return nil
}

func (m *Connection) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

func (m *Connection) GetConnMethod() string {
	if m != nil {
		return m.ConnMethod
	}
	return ""
}

type NetworkServiceStatus struct {
	OperStatus              string                            `protobuf:"bytes,2,opt,name=oper_status,json=operStatus,proto3" json:"oper_status,omitempty"`
	Msg                     []string                          `protobuf:"bytes,3,rep,name=msg,proto3" json:"msg,omitempty"`
	RenderedVppAgentEntries map[string]*RenderedVppAgentEntry `protobuf:"bytes,4,rep,name=rendered_vpp_agent_entries,json=renderedVppAgentEntries,proto3" json:"rendered_vpp_agent_entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Interfaces              map[string]*InterfaceStatus       `protobuf:"bytes,5,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral    struct{}                          `json:"-"`
	XXX_unrecognized        []byte                            `json:"-"`
	XXX_sizecache           int32                             `json:"-"`
}

func (m *NetworkServiceStatus) Reset()         { *m = NetworkServiceStatus{} }
func (m *NetworkServiceStatus) String() string { return proto.CompactTextString(m) }
func (*NetworkServiceStatus) ProtoMessage()    {}
func (*NetworkServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{16}
}
func (m *NetworkServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkServiceStatus.Unmarshal(m, b)
}
func (m *NetworkServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkServiceStatus.Marshal(b, m, deterministic)
}
func (dst *NetworkServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkServiceStatus.Merge(dst, src)
}
func (m *NetworkServiceStatus) XXX_Size() int {
	return xxx_messageInfo_NetworkServiceStatus.Size(m)
}
func (m *NetworkServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkServiceStatus proto.InternalMessageInfo

func (m *NetworkServiceStatus) GetOperStatus() string {
	if m != nil {
		return m.OperStatus
	}
	return ""
}

func (m *NetworkServiceStatus) GetMsg() []string {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *NetworkServiceStatus) GetRenderedVppAgentEntries() map[string]*RenderedVppAgentEntry {
	if m != nil {
		return m.RenderedVppAgentEntries
	}
	return nil
}

func (m *NetworkServiceStatus) GetInterfaces() map[string]*InterfaceStatus {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type NetworkServiceSpec struct {
	NetworkPods          []*NetworkPod `protobuf:"bytes,3,rep,name=network_pods,json=networkPods,proto3" json:"network_pods,omitempty"`
	Connections          []*Connection `protobuf:"bytes,4,rep,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NetworkServiceSpec) Reset()         { *m = NetworkServiceSpec{} }
func (m *NetworkServiceSpec) String() string { return proto.CompactTextString(m) }
func (*NetworkServiceSpec) ProtoMessage()    {}
func (*NetworkServiceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{17}
}
func (m *NetworkServiceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkServiceSpec.Unmarshal(m, b)
}
func (m *NetworkServiceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkServiceSpec.Marshal(b, m, deterministic)
}
func (dst *NetworkServiceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkServiceSpec.Merge(dst, src)
}
func (m *NetworkServiceSpec) XXX_Size() int {
	return xxx_messageInfo_NetworkServiceSpec.Size(m)
}
func (m *NetworkServiceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkServiceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkServiceSpec proto.InternalMessageInfo

func (m *NetworkServiceSpec) GetNetworkPods() []*NetworkPod {
	if m != nil {
		return m.NetworkPods
	}
	return nil
}

func (m *NetworkServiceSpec) GetConnections() []*Connection {
	if m != nil {
		return m.Connections
	}
	return nil
}

type NetworkService struct {
	Metadata             *MetaDataType         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *NetworkServiceSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *NetworkServiceStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NetworkService) Reset()         { *m = NetworkService{} }
func (m *NetworkService) String() string { return proto.CompactTextString(m) }
func (*NetworkService) ProtoMessage()    {}
func (*NetworkService) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{18}
}
func (m *NetworkService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkService.Unmarshal(m, b)
}
func (m *NetworkService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkService.Marshal(b, m, deterministic)
}
func (dst *NetworkService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkService.Merge(dst, src)
}
func (m *NetworkService) XXX_Size() int {
	return xxx_messageInfo_NetworkService.Size(m)
}
func (m *NetworkService) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkService.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkService proto.InternalMessageInfo

func (m *NetworkService) GetMetadata() *MetaDataType {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NetworkService) GetSpec() *NetworkServiceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *NetworkService) GetStatus() *NetworkServiceStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type NetworkNodeOverlayStatus struct {
	Status                  string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                     []string                          `protobuf:"bytes,2,rep,name=msg,proto3" json:"msg,omitempty"`
	RenderedVppAgentEntries map[string]*RenderedVppAgentEntry `protobuf:"bytes,3,rep,name=rendered_vpp_agent_entries,json=renderedVppAgentEntries,proto3" json:"rendered_vpp_agent_entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral    struct{}                          `json:"-"`
	XXX_unrecognized        []byte                            `json:"-"`
	XXX_sizecache           int32                             `json:"-"`
}

func (m *NetworkNodeOverlayStatus) Reset()         { *m = NetworkNodeOverlayStatus{} }
func (m *NetworkNodeOverlayStatus) String() string { return proto.CompactTextString(m) }
func (*NetworkNodeOverlayStatus) ProtoMessage()    {}
func (*NetworkNodeOverlayStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{19}
}
func (m *NetworkNodeOverlayStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkNodeOverlayStatus.Unmarshal(m, b)
}
func (m *NetworkNodeOverlayStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkNodeOverlayStatus.Marshal(b, m, deterministic)
}
func (dst *NetworkNodeOverlayStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkNodeOverlayStatus.Merge(dst, src)
}
func (m *NetworkNodeOverlayStatus) XXX_Size() int {
	return xxx_messageInfo_NetworkNodeOverlayStatus.Size(m)
}
func (m *NetworkNodeOverlayStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkNodeOverlayStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkNodeOverlayStatus proto.InternalMessageInfo

func (m *NetworkNodeOverlayStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NetworkNodeOverlayStatus) GetMsg() []string {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *NetworkNodeOverlayStatus) GetRenderedVppAgentEntries() map[string]*RenderedVppAgentEntry {
	if m != nil {
		return m.RenderedVppAgentEntries
	}
	return nil
}

type NetworkNodeOverlaySpec struct {
	ServiceMeshType       string                                        `protobuf:"bytes,1,opt,name=service_mesh_type,json=serviceMeshType,proto3" json:"service_mesh_type,omitempty"`
	ConnectionType        string                                        `protobuf:"bytes,2,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	VxlanHubAndSpokeParms *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms `protobuf:"bytes,3,opt,name=vxlan_hub_and_spoke_parms,json=vxlanHubAndSpokeParms,proto3" json:"vxlan_hub_and_spoke_parms,omitempty"`
	VxlanMeshParms        *NetworkNodeOverlaySpec_VxlanMeshParms        `protobuf:"bytes,4,opt,name=vxlan_mesh_parms,json=vxlanMeshParms,proto3" json:"vxlan_mesh_parms,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                                      `json:"-"`
	XXX_unrecognized      []byte                                        `json:"-"`
	XXX_sizecache         int32                                         `json:"-"`
}

func (m *NetworkNodeOverlaySpec) Reset()         { *m = NetworkNodeOverlaySpec{} }
func (m *NetworkNodeOverlaySpec) String() string { return proto.CompactTextString(m) }
func (*NetworkNodeOverlaySpec) ProtoMessage()    {}
func (*NetworkNodeOverlaySpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{20}
}
func (m *NetworkNodeOverlaySpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkNodeOverlaySpec.Unmarshal(m, b)
}
func (m *NetworkNodeOverlaySpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkNodeOverlaySpec.Marshal(b, m, deterministic)
}
func (dst *NetworkNodeOverlaySpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkNodeOverlaySpec.Merge(dst, src)
}
func (m *NetworkNodeOverlaySpec) XXX_Size() int {
	return xxx_messageInfo_NetworkNodeOverlaySpec.Size(m)
}
func (m *NetworkNodeOverlaySpec) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkNodeOverlaySpec.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkNodeOverlaySpec proto.InternalMessageInfo

func (m *NetworkNodeOverlaySpec) GetServiceMeshType() string {
	if m != nil {
		return m.ServiceMeshType
	}
	return ""
}

func (m *NetworkNodeOverlaySpec) GetConnectionType() string {
	if m != nil {
		return m.ConnectionType
	}
	return ""
}

func (m *NetworkNodeOverlaySpec) GetVxlanHubAndSpokeParms() *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms {
	if m != nil {
		return m.VxlanHubAndSpokeParms
	}
	return nil
}

func (m *NetworkNodeOverlaySpec) GetVxlanMeshParms() *NetworkNodeOverlaySpec_VxlanMeshParms {
	if m != nil {
		return m.VxlanMeshParms
	}
	return nil
}

type NetworkNodeOverlaySpec_VxlanHubAndSpokeParms struct {
	HubNodeName                string   `protobuf:"bytes,1,opt,name=hub_node_name,json=hubNodeName,proto3" json:"hub_node_name,omitempty"`
	Vni                        uint32   `protobuf:"varint,2,opt,name=vni,proto3" json:"vni,omitempty"`
	LoopbackIpamPoolName       string   `protobuf:"bytes,3,opt,name=loopback_ipam_pool_name,json=loopbackIpamPoolName,proto3" json:"loopback_ipam_pool_name,omitempty"`
	CreateLoopbackInterface    bool     `protobuf:"varint,4,opt,name=create_loopback_interface,json=createLoopbackInterface,proto3" json:"create_loopback_interface,omitempty"`
	CreateLoopbackStaticRoutes bool     `protobuf:"varint,5,opt,name=create_loopback_static_routes,json=createLoopbackStaticRoutes,proto3" json:"create_loopback_static_routes,omitempty"`
	NetworkNodeInterfaceLabel  string   `protobuf:"bytes,6,opt,name=network_node_interface_label,json=networkNodeInterfaceLabel,proto3" json:"network_node_interface_label,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) Reset() {
	*m = NetworkNodeOverlaySpec_VxlanHubAndSpokeParms{}
}
func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) String() string {
	return proto.CompactTextString(m)
}
func (*NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) ProtoMessage() {}
func (*NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{20, 0}
}
func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkNodeOverlaySpec_VxlanHubAndSpokeParms.Unmarshal(m, b)
}
func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkNodeOverlaySpec_VxlanHubAndSpokeParms.Marshal(b, m, deterministic)
}
func (dst *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkNodeOverlaySpec_VxlanHubAndSpokeParms.Merge(dst, src)
}
func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) XXX_Size() int {
	return xxx_messageInfo_NetworkNodeOverlaySpec_VxlanHubAndSpokeParms.Size(m)
}
func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkNodeOverlaySpec_VxlanHubAndSpokeParms.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkNodeOverlaySpec_VxlanHubAndSpokeParms proto.InternalMessageInfo

func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) GetHubNodeName() string {
	if m != nil {
		return m.HubNodeName
	}
	return ""
}

func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) GetVni() uint32 {
	if m != nil {
		return m.Vni
	}
	return 0
}

func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) GetLoopbackIpamPoolName() string {
	if m != nil {
		return m.LoopbackIpamPoolName
	}
	return ""
}

func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) GetCreateLoopbackInterface() bool {
	if m != nil {
		return m.CreateLoopbackInterface
	}
	return false
}

func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) GetCreateLoopbackStaticRoutes() bool {
	if m != nil {
		return m.CreateLoopbackStaticRoutes
	}
	return false
}

func (m *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) GetNetworkNodeInterfaceLabel() string {
	if m != nil {
		return m.NetworkNodeInterfaceLabel
	}
	return ""
}

type NetworkNodeOverlaySpec_VxlanMeshParms struct {
	VniRangeStart              uint32   `protobuf:"varint,1,opt,name=vni_range_start,json=vniRangeStart,proto3" json:"vni_range_start,omitempty"`
	VniRangeEnd                uint32   `protobuf:"varint,2,opt,name=vni_range_end,json=vniRangeEnd,proto3" json:"vni_range_end,omitempty"`
	LoopbackIpamPoolName       string   `protobuf:"bytes,3,opt,name=loopback_ipam_pool_name,json=loopbackIpamPoolName,proto3" json:"loopback_ipam_pool_name,omitempty"`
	CreateLoopbackInterface    bool     `protobuf:"varint,4,opt,name=create_loopback_interface,json=createLoopbackInterface,proto3" json:"create_loopback_interface,omitempty"`
	CreateLoopbackStaticRoutes bool     `protobuf:"varint,5,opt,name=create_loopback_static_routes,json=createLoopbackStaticRoutes,proto3" json:"create_loopback_static_routes,omitempty"`
	NetworkNodeInterfaceLabel  string   `protobuf:"bytes,6,opt,name=network_node_interface_label,json=networkNodeInterfaceLabel,proto3" json:"network_node_interface_label,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *NetworkNodeOverlaySpec_VxlanMeshParms) Reset()         { *m = NetworkNodeOverlaySpec_VxlanMeshParms{} }
func (m *NetworkNodeOverlaySpec_VxlanMeshParms) String() string { return proto.CompactTextString(m) }
func (*NetworkNodeOverlaySpec_VxlanMeshParms) ProtoMessage()    {}
func (*NetworkNodeOverlaySpec_VxlanMeshParms) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{20, 1}
}
func (m *NetworkNodeOverlaySpec_VxlanMeshParms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkNodeOverlaySpec_VxlanMeshParms.Unmarshal(m, b)
}
func (m *NetworkNodeOverlaySpec_VxlanMeshParms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkNodeOverlaySpec_VxlanMeshParms.Marshal(b, m, deterministic)
}
func (dst *NetworkNodeOverlaySpec_VxlanMeshParms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkNodeOverlaySpec_VxlanMeshParms.Merge(dst, src)
}
func (m *NetworkNodeOverlaySpec_VxlanMeshParms) XXX_Size() int {
	return xxx_messageInfo_NetworkNodeOverlaySpec_VxlanMeshParms.Size(m)
}
func (m *NetworkNodeOverlaySpec_VxlanMeshParms) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkNodeOverlaySpec_VxlanMeshParms.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkNodeOverlaySpec_VxlanMeshParms proto.InternalMessageInfo

func (m *NetworkNodeOverlaySpec_VxlanMeshParms) GetVniRangeStart() uint32 {
	if m != nil {
		return m.VniRangeStart
	}
	return 0
}

func (m *NetworkNodeOverlaySpec_VxlanMeshParms) GetVniRangeEnd() uint32 {
	if m != nil {
		return m.VniRangeEnd
	}
	return 0
}

func (m *NetworkNodeOverlaySpec_VxlanMeshParms) GetLoopbackIpamPoolName() string {
	if m != nil {
		return m.LoopbackIpamPoolName
	}
	return ""
}

func (m *NetworkNodeOverlaySpec_VxlanMeshParms) GetCreateLoopbackInterface() bool {
	if m != nil {
		return m.CreateLoopbackInterface
	}
	return false
}

func (m *NetworkNodeOverlaySpec_VxlanMeshParms) GetCreateLoopbackStaticRoutes() bool {
	if m != nil {
		return m.CreateLoopbackStaticRoutes
	}
	return false
}

func (m *NetworkNodeOverlaySpec_VxlanMeshParms) GetNetworkNodeInterfaceLabel() string {
	if m != nil {
		return m.NetworkNodeInterfaceLabel
	}
	return ""
}

type NetworkNodeOverlay struct {
	Metadata             *MetaDataType             `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *NetworkNodeOverlaySpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *NetworkNodeOverlayStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NetworkNodeOverlay) Reset()         { *m = NetworkNodeOverlay{} }
func (m *NetworkNodeOverlay) String() string { return proto.CompactTextString(m) }
func (*NetworkNodeOverlay) ProtoMessage()    {}
func (*NetworkNodeOverlay) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{21}
}
func (m *NetworkNodeOverlay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkNodeOverlay.Unmarshal(m, b)
}
func (m *NetworkNodeOverlay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkNodeOverlay.Marshal(b, m, deterministic)
}
func (dst *NetworkNodeOverlay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkNodeOverlay.Merge(dst, src)
}
func (m *NetworkNodeOverlay) XXX_Size() int {
	return xxx_messageInfo_NetworkNodeOverlay.Size(m)
}
func (m *NetworkNodeOverlay) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkNodeOverlay.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkNodeOverlay proto.InternalMessageInfo

func (m *NetworkNodeOverlay) GetMetadata() *MetaDataType {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NetworkNodeOverlay) GetSpec() *NetworkNodeOverlaySpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *NetworkNodeOverlay) GetStatus() *NetworkNodeOverlayStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// NetworkNodeSpec extends the k8s node
type NetworkNodeSpec struct {
	K8SNodeName          string       `protobuf:"bytes,1,opt,name=k8s_node_name,json=k8sNodeName,proto3" json:"k8s_node_name,omitempty"`
	NodeType             string       `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Interfaces           []*Interface `protobuf:"bytes,4,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	L2Bds                []*L2BD      `protobuf:"bytes,5,rep,name=l2bds,proto3" json:"l2bds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NetworkNodeSpec) Reset()         { *m = NetworkNodeSpec{} }
func (m *NetworkNodeSpec) String() string { return proto.CompactTextString(m) }
func (*NetworkNodeSpec) ProtoMessage()    {}
func (*NetworkNodeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{22}
}
func (m *NetworkNodeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkNodeSpec.Unmarshal(m, b)
}
func (m *NetworkNodeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkNodeSpec.Marshal(b, m, deterministic)
}
func (dst *NetworkNodeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkNodeSpec.Merge(dst, src)
}
func (m *NetworkNodeSpec) XXX_Size() int {
	return xxx_messageInfo_NetworkNodeSpec.Size(m)
}
func (m *NetworkNodeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkNodeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkNodeSpec proto.InternalMessageInfo

func (m *NetworkNodeSpec) GetK8SNodeName() string {
	if m != nil {
		return m.K8SNodeName
	}
	return ""
}

func (m *NetworkNodeSpec) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *NetworkNodeSpec) GetInterfaces() []*Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *NetworkNodeSpec) GetL2Bds() []*L2BD {
	if m != nil {
		return m.L2Bds
	}
	return nil
}

type NetworkNodeStatus struct {
	Status                  string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                     []string                          `protobuf:"bytes,2,rep,name=msg,proto3" json:"msg,omitempty"`
	RenderedVppAgentEntries map[string]*RenderedVppAgentEntry `protobuf:"bytes,3,rep,name=rendered_vpp_agent_entries,json=renderedVppAgentEntries,proto3" json:"rendered_vpp_agent_entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Interfaces              map[string]*InterfaceStatus       `protobuf:"bytes,5,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral    struct{}                          `json:"-"`
	XXX_unrecognized        []byte                            `json:"-"`
	XXX_sizecache           int32                             `json:"-"`
}

func (m *NetworkNodeStatus) Reset()         { *m = NetworkNodeStatus{} }
func (m *NetworkNodeStatus) String() string { return proto.CompactTextString(m) }
func (*NetworkNodeStatus) ProtoMessage()    {}
func (*NetworkNodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{23}
}
func (m *NetworkNodeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkNodeStatus.Unmarshal(m, b)
}
func (m *NetworkNodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkNodeStatus.Marshal(b, m, deterministic)
}
func (dst *NetworkNodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkNodeStatus.Merge(dst, src)
}
func (m *NetworkNodeStatus) XXX_Size() int {
	return xxx_messageInfo_NetworkNodeStatus.Size(m)
}
func (m *NetworkNodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkNodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkNodeStatus proto.InternalMessageInfo

func (m *NetworkNodeStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NetworkNodeStatus) GetMsg() []string {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *NetworkNodeStatus) GetRenderedVppAgentEntries() map[string]*RenderedVppAgentEntry {
	if m != nil {
		return m.RenderedVppAgentEntries
	}
	return nil
}

func (m *NetworkNodeStatus) GetInterfaces() map[string]*InterfaceStatus {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type NetworkNode struct {
	Metadata             *MetaDataType      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *NetworkNodeSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *NetworkNodeStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NetworkNode) Reset()         { *m = NetworkNode{} }
func (m *NetworkNode) String() string { return proto.CompactTextString(m) }
func (*NetworkNode) ProtoMessage()    {}
func (*NetworkNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{24}
}
func (m *NetworkNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkNode.Unmarshal(m, b)
}
func (m *NetworkNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkNode.Marshal(b, m, deterministic)
}
func (dst *NetworkNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkNode.Merge(dst, src)
}
func (m *NetworkNode) XXX_Size() int {
	return xxx_messageInfo_NetworkNode.Size(m)
}
func (m *NetworkNode) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkNode.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkNode proto.InternalMessageInfo

func (m *NetworkNode) GetMetadata() *MetaDataType {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NetworkNode) GetSpec() *NetworkNodeSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *NetworkNode) GetStatus() *NetworkNodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// MetaDataType generic parms for all controller high level objects
type MetaDataType struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MetaDataType) Reset()         { *m = MetaDataType{} }
func (m *MetaDataType) String() string { return proto.CompactTextString(m) }
func (*MetaDataType) ProtoMessage()    {}
func (*MetaDataType) Descriptor() ([]byte, []int) {
	return fileDescriptor_controller_43bca1d4550c23d4, []int{25}
}
func (m *MetaDataType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaDataType.Unmarshal(m, b)
}
func (m *MetaDataType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaDataType.Marshal(b, m, deterministic)
}
func (dst *MetaDataType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaDataType.Merge(dst, src)
}
func (m *MetaDataType) XXX_Size() int {
	return xxx_messageInfo_MetaDataType.Size(m)
}
func (m *MetaDataType) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaDataType.DiscardUnknown(m)
}

var xxx_messageInfo_MetaDataType proto.InternalMessageInfo

func (m *MetaDataType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaDataType) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*L3VRFRoute)(nil), "controller.L3VRFRoute")
	proto.RegisterType((*L3ArpEntry)(nil), "controller.L3ArpEntry")
	proto.RegisterType((*L2FIBEntry)(nil), "controller.L2FIBEntry")
	proto.RegisterType((*BDParms)(nil), "controller.BDParms")
	proto.RegisterType((*L2BD)(nil), "controller.L2BD")
	proto.RegisterType((*IPAMPoolStatus)(nil), "controller.IPAMPoolStatus")
	proto.RegisterMapType((map[string]string)(nil), "controller.IPAMPoolStatus.AddressesEntry")
	proto.RegisterType((*IPAMPoolSpec)(nil), "controller.IPAMPoolSpec")
	proto.RegisterType((*IPAMPool)(nil), "controller.IPAMPool")
	proto.RegisterType((*SystemParameters)(nil), "controller.SystemParameters")
	proto.RegisterType((*NetworkPodToNodeMap)(nil), "controller.NetworkPodToNodeMap")
	proto.RegisterType((*RenderedVppAgentEntry)(nil), "controller.RenderedVppAgentEntry")
	proto.RegisterType((*InterfaceStatus)(nil), "controller.InterfaceStatus")
	proto.RegisterMapType((map[string]uint32)(nil), "controller.InterfaceStatus.IpamPoolNumsEntry")
	proto.RegisterType((*Interface)(nil), "controller.Interface")
	proto.RegisterType((*Interface_MemIFParms)(nil), "controller.Interface.MemIFParms")
	proto.RegisterType((*Interface_TapParms)(nil), "controller.Interface.TapParms")
	proto.RegisterType((*Interface_Forwarding)(nil), "controller.Interface.Forwarding")
	proto.RegisterType((*Interface_LinuxNamespace)(nil), "controller.Interface.LinuxNamespace")
	proto.RegisterType((*Interface_RxPlacementSettings)(nil), "controller.Interface.RxPlacementSettings")
	proto.RegisterType((*NetworkPodSpec)(nil), "controller.NetworkPodSpec")
	proto.RegisterType((*NetworkPod)(nil), "controller.NetworkPod")
	proto.RegisterType((*Connection)(nil), "controller.Connection")
	proto.RegisterType((*NetworkServiceStatus)(nil), "controller.NetworkServiceStatus")
	proto.RegisterMapType((map[string]*InterfaceStatus)(nil), "controller.NetworkServiceStatus.InterfacesEntry")
	proto.RegisterMapType((map[string]*RenderedVppAgentEntry)(nil), "controller.NetworkServiceStatus.RenderedVppAgentEntriesEntry")
	proto.RegisterType((*NetworkServiceSpec)(nil), "controller.NetworkServiceSpec")
	proto.RegisterType((*NetworkService)(nil), "controller.NetworkService")
	proto.RegisterType((*NetworkNodeOverlayStatus)(nil), "controller.NetworkNodeOverlayStatus")
	proto.RegisterMapType((map[string]*RenderedVppAgentEntry)(nil), "controller.NetworkNodeOverlayStatus.RenderedVppAgentEntriesEntry")
	proto.RegisterType((*NetworkNodeOverlaySpec)(nil), "controller.NetworkNodeOverlaySpec")
	proto.RegisterType((*NetworkNodeOverlaySpec_VxlanHubAndSpokeParms)(nil), "controller.NetworkNodeOverlaySpec.VxlanHubAndSpokeParms")
	proto.RegisterType((*NetworkNodeOverlaySpec_VxlanMeshParms)(nil), "controller.NetworkNodeOverlaySpec.VxlanMeshParms")
	proto.RegisterType((*NetworkNodeOverlay)(nil), "controller.NetworkNodeOverlay")
	proto.RegisterType((*NetworkNodeSpec)(nil), "controller.NetworkNodeSpec")
	proto.RegisterType((*NetworkNodeStatus)(nil), "controller.NetworkNodeStatus")
	proto.RegisterMapType((map[string]*InterfaceStatus)(nil), "controller.NetworkNodeStatus.InterfacesEntry")
	proto.RegisterMapType((map[string]*RenderedVppAgentEntry)(nil), "controller.NetworkNodeStatus.RenderedVppAgentEntriesEntry")
	proto.RegisterType((*NetworkNode)(nil), "controller.NetworkNode")
	proto.RegisterType((*MetaDataType)(nil), "controller.MetaDataType")
	proto.RegisterMapType((map[string]string)(nil), "controller.MetaDataType.LabelsEntry")
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor_controller_43bca1d4550c23d4) }

var fileDescriptor_controller_43bca1d4550c23d4 = []byte{
	// 2557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x59, 0xcf, 0x6f, 0x1c, 0x49,
	0xf5, 0xd7, 0x78, 0xec, 0xf1, 0xcc, 0x9b, 0x1f, 0x76, 0xda, 0xeb, 0x64, 0x3c, 0xce, 0x66, 0xbd,
	0xfd, 0xcd, 0x77, 0x93, 0x45, 0xc4, 0xb0, 0x13, 0x16, 0x9c, 0x6c, 0x56, 0x2b, 0x07, 0xc7, 0xac,
	0x85, 0xc7, 0x98, 0x76, 0x08, 0x12, 0x3f, 0xd4, 0xaa, 0x99, 0xae, 0xb1, 0x5b, 0xee, 0xae, 0x6a,
	0xaa, 0x6a, 0xc6, 0x76, 0x04, 0xdc, 0xe1, 0x1f, 0x40, 0x82, 0x1b, 0xe2, 0xc6, 0x69, 0x05, 0x7f,
	0x00, 0x07, 0xc4, 0x81, 0x13, 0x12, 0x27, 0xc4, 0x8d, 0x13, 0x47, 0xfe, 0x02, 0x84, 0xea, 0x47,
	0x77, 0x57, 0xdb, 0x6d, 0x3b, 0x09, 0x12, 0x97, 0xbd, 0x75, 0xbd, 0x7a, 0x55, 0xf5, 0xea, 0xfd,
	0xf8, 0xbc, 0xf7, 0xaa, 0x61, 0x71, 0x44, 0x89, 0x60, 0x34, 0x8a, 0x30, 0x5b, 0x4f, 0x18, 0x15,
	0xd4, 0x81, 0x9c, 0xe2, 0xfe, 0xab, 0x02, 0xb0, 0xfb, 0xf0, 0x85, 0xb7, 0xed, 0xd1, 0x89, 0xc0,
	0xce, 0x32, 0xd4, 0xa6, 0x6c, 0xec, 0x87, 0x41, 0xb7, 0xb2, 0x56, 0xb9, 0xdf, 0xf6, 0xe6, 0xa6,
	0x6c, 0xbc, 0x13, 0x38, 0x6b, 0xd0, 0x0c, 0x30, 0x1f, 0xb1, 0x30, 0x11, 0x21, 0x25, 0xdd, 0x99,
	0xb5, 0xca, 0xfd, 0x86, 0x67, 0x93, 0x9c, 0x3b, 0xd0, 0x0c, 0xb8, 0xf0, 0xc3, 0xc4, 0x47, 0x41,
	0xc0, 0xba, 0x55, 0xc5, 0xd1, 0x08, 0xb8, 0xd8, 0x49, 0x36, 0x83, 0x80, 0x39, 0x2e, 0xb4, 0x09,
	0x3e, 0x15, 0xfe, 0x11, 0x35, 0x1c, 0xb3, 0x7a, 0x0f, 0x49, 0xfc, 0x94, 0x6a, 0x9e, 0x07, 0xe0,
	0xd0, 0x89, 0x38, 0xa4, 0x21, 0x39, 0xf4, 0x43, 0x22, 0x30, 0x1b, 0xa3, 0x11, 0xee, 0xce, 0x29,
	0xc6, 0x1b, 0xe9, 0xcc, 0x4e, 0x3a, 0xe1, 0xdc, 0x84, 0xda, 0x09, 0x0e, 0x0f, 0x8f, 0x44, 0xb7,
	0xa6, 0x64, 0x35, 0x23, 0xe7, 0x0e, 0x40, 0xc2, 0xf0, 0x18, 0x33, 0x4c, 0x46, 0xb8, 0x3b, 0xaf,
	0xe6, 0x2c, 0x8a, 0xfb, 0x13, 0x79, 0xe3, 0x4d, 0x96, 0x3c, 0x23, 0x82, 0x9d, 0x39, 0x6f, 0x03,
	0x18, 0xa1, 0x31, 0xe7, 0xea, 0xd6, 0x0d, 0xaf, 0x11, 0x2a, 0x81, 0x30, 0xe7, 0xce, 0xbb, 0xd0,
	0x4a, 0x8e, 0xce, 0x78, 0xc6, 0x60, 0xae, 0x2e, 0x69, 0x29, 0x4b, 0xb9, 0xd8, 0xd5, 0x4b, 0xc4,
	0x76, 0x7f, 0x29, 0x35, 0xde, 0xdf, 0xde, 0x79, 0xaa, 0xcf, 0xbf, 0x0f, 0x8b, 0x01, 0xe6, 0xc2,
	0x8f, 0xd1, 0xe8, 0x9c, 0x14, 0x1d, 0x49, 0x1f, 0xa0, 0x51, 0x7a, 0xce, 0x2d, 0x98, 0x1f, 0x06,
	0x3e, 0x41, 0x31, 0x36, 0x52, 0xd4, 0x86, 0xc1, 0x1e, 0x8a, 0xb1, 0xf3, 0x0e, 0x34, 0x73, 0x01,
	0xc6, 0xe6, 0x64, 0xc8, 0x4e, 0x1e, 0x4b, 0x4d, 0xa1, 0x91, 0xb2, 0x9c, 0xd6, 0xba, 0x19, 0x39,
	0x8b, 0x50, 0x1d, 0x4e, 0x43, 0xa5, 0xe1, 0xba, 0x27, 0x3f, 0xdd, 0x7f, 0x56, 0x60, 0xfe, 0xe9,
	0xd6, 0x3e, 0x62, 0x31, 0x77, 0x1c, 0x98, 0x55, 0x87, 0x69, 0x69, 0xd4, 0xb7, 0xf3, 0x16, 0xcc,
	0x8d, 0x23, 0x4a, 0x03, 0x25, 0x41, 0xdd, 0xd3, 0x03, 0xa7, 0x0f, 0xcb, 0x13, 0x72, 0x4c, 0xe8,
	0x09, 0xf1, 0x27, 0x24, 0x1c, 0x21, 0x2e, 0x7c, 0xcd, 0x55, 0x55, 0x5c, 0x4b, 0x66, 0xf2, 0x3b,
	0x7a, 0x6e, 0x5b, 0xad, 0xe9, 0xc2, 0xfc, 0x98, 0xb2, 0x13, 0xc4, 0x02, 0x25, 0x54, 0xdd, 0x4b,
	0x87, 0xf2, 0x8c, 0x08, 0x23, 0x46, 0x8c, 0x5c, 0x7a, 0xe0, 0xdc, 0x83, 0x05, 0xc4, 0x12, 0x5f,
	0x60, 0x16, 0x87, 0x04, 0xa9, 0xcb, 0xd4, 0xd4, 0x7c, 0x07, 0xb1, 0xe4, 0x79, 0x4e, 0x75, 0xde,
	0x83, 0x05, 0xa5, 0xcb, 0x43, 0xec, 0xc7, 0x21, 0x99, 0x08, 0xcc, 0x8d, 0x0f, 0xb4, 0x63, 0x34,
	0xda, 0x3c, 0xc4, 0x03, 0x4d, 0x74, 0x29, 0xcc, 0xee, 0xf6, 0x9f, 0x6e, 0x95, 0x5e, 0x73, 0x1d,
	0xea, 0xc3, 0xc0, 0x4f, 0xa4, 0x1a, 0xd4, 0x4d, 0x9b, 0xfd, 0xa5, 0x75, 0x2b, 0x8c, 0x8c, 0x86,
	0xbc, 0xf9, 0x61, 0xa0, 0x55, 0xf5, 0x7f, 0xd0, 0x8e, 0xfa, 0xc3, 0xc0, 0x17, 0x38, 0x4e, 0x22,
	0x24, 0x52, 0xeb, 0xb7, 0x24, 0xf1, 0xb9, 0xa1, 0xb9, 0xbf, 0xa8, 0x40, 0x67, 0x67, 0x7f, 0x73,
	0xb0, 0x4f, 0x69, 0x74, 0x20, 0x90, 0x98, 0x70, 0xe7, 0x1b, 0xd0, 0x30, 0x36, 0xc7, 0xd2, 0xea,
	0xd5, 0xfb, 0xcd, 0xfe, 0xfb, 0xf6, 0x41, 0x45, 0xf6, 0xf5, 0xcd, 0x94, 0x57, 0xb9, 0x8e, 0x97,
	0xaf, 0xed, 0x3d, 0x81, 0x4e, 0x71, 0x52, 0xda, 0xf6, 0x18, 0x9f, 0x99, 0x5b, 0xc9, 0x4f, 0xa9,
	0xd7, 0x29, 0x8a, 0x26, 0xa9, 0xf7, 0xe8, 0xc1, 0xe3, 0x99, 0x8d, 0x8a, 0xfb, 0x63, 0x68, 0x65,
	0x27, 0x25, 0x78, 0x24, 0x39, 0xf9, 0x88, 0x26, 0x19, 0xa7, 0x1a, 0x48, 0x8b, 0x11, 0x2c, 0x4e,
	0x28, 0x3b, 0x36, 0xd7, 0x4b, 0x87, 0xd2, 0x01, 0xb9, 0x40, 0x4c, 0xf8, 0x0c, 0x91, 0x43, 0xac,
	0xec, 0xd9, 0xf6, 0x40, 0x91, 0x3c, 0x49, 0x71, 0x56, 0xa1, 0x81, 0x49, 0x60, 0xa6, 0xe7, 0xd4,
	0x74, 0x1d, 0x93, 0x40, 0x4d, 0xba, 0xbf, 0xae, 0x40, 0x3d, 0x3d, 0xde, 0xf9, 0x0a, 0xd4, 0x63,
	0x2c, 0x50, 0x80, 0x04, 0x52, 0xb2, 0x37, 0xfb, 0x5d, 0x5b, 0x21, 0x03, 0x2c, 0xd0, 0x16, 0x12,
	0xe8, 0xf9, 0x59, 0x82, 0xbd, 0x8c, 0xd3, 0xf9, 0x22, 0xcc, 0xf2, 0x04, 0x8f, 0x8c, 0xad, 0xba,
	0xa5, 0x2a, 0x4c, 0xf0, 0xc8, 0x53, 0x5c, 0x4e, 0x1f, 0x6a, 0x5c, 0x29, 0x54, 0xdd, 0xa3, 0xd9,
	0xef, 0x5d, 0xae, 0x72, 0xcf, 0x70, 0xba, 0x7f, 0x9a, 0x81, 0xc5, 0x83, 0x33, 0x2e, 0x70, 0xbc,
	0x8f, 0x18, 0x8a, 0xb1, 0xc0, 0x8c, 0x4b, 0x1d, 0xc7, 0x62, 0x62, 0xa0, 0x52, 0x7e, 0x4a, 0x2f,
	0x8d, 0x71, 0x1c, 0x8e, 0xfd, 0x20, 0x64, 0x78, 0x24, 0x28, 0x3b, 0x33, 0x3a, 0xec, 0x28, 0xf2,
	0x56, 0x4a, 0x75, 0x3e, 0x86, 0xd5, 0x00, 0x8f, 0xd1, 0x24, 0x12, 0xbe, 0x3c, 0x21, 0x1c, 0xf9,
	0x4c, 0x02, 0xb0, 0x6f, 0x10, 0xad, 0xaa, 0xb6, 0xec, 0x1a, 0x96, 0x03, 0xc5, 0xa1, 0x10, 0xfa,
	0xbb, 0x1a, 0xe3, 0x9e, 0xc1, 0x3b, 0xa5, 0xcb, 0x2d, 0xe0, 0xd3, 0x56, 0xb8, 0x7d, 0x71, 0x8b,
	0xfd, 0x8c, 0xc7, 0x79, 0x0c, 0x9d, 0x82, 0xdf, 0xf2, 0xee, 0x9c, 0x72, 0xc2, 0x52, 0x6f, 0x6f,
	0xdb, 0xde, 0xac, 0xe0, 0x88, 0x9d, 0xfa, 0x31, 0x0d, 0x34, 0xc6, 0x36, 0xbc, 0x1a, 0x3b, 0x1d,
	0xd0, 0x00, 0x3b, 0xb7, 0x01, 0xe2, 0x90, 0xf8, 0x26, 0x8f, 0xd4, 0xb5, 0xb5, 0xe3, 0x90, 0xbc,
	0x90, 0xa9, 0xc4, 0xfd, 0x08, 0x96, 0xf6, 0xb4, 0xdb, 0xec, 0xd3, 0xe0, 0x39, 0xdd, 0xa3, 0x01,
	0x1e, 0xa0, 0x44, 0xaa, 0x32, 0xa1, 0x41, 0xea, 0xae, 0x09, 0x0d, 0x54, 0x5c, 0xca, 0xcd, 0x67,
	0x4c, 0x5c, 0xd2, 0x00, 0xbb, 0x08, 0x96, 0x3d, 0x4c, 0x02, 0xcc, 0x70, 0xf0, 0x22, 0x49, 0x36,
	0x0f, 0x31, 0x11, 0xda, 0xdb, 0x5d, 0x68, 0x4f, 0x93, 0x44, 0x06, 0x3d, 0x11, 0x7e, 0xee, 0xf7,
	0xcd, 0xa9, 0xe1, 0xfa, 0x26, 0x3e, 0x73, 0xee, 0x42, 0x27, 0xe7, 0x11, 0x67, 0x99, 0x7b, 0xb7,
	0x52, 0x26, 0xe9, 0x54, 0xee, 0x9f, 0xab, 0xb0, 0x90, 0x81, 0xb5, 0x09, 0xd3, 0x32, 0x88, 0xb8,
	0x99, 0x39, 0x91, 0x01, 0x63, 0x3d, 0x52, 0x3e, 0xc1, 0x0f, 0xbb, 0xd5, 0xb5, 0xaa, 0xbc, 0x48,
	0xcc, 0x0f, 0x65, 0x74, 0xd8, 0xe0, 0xae, 0x21, 0x18, 0xe2, 0x1c, 0xd8, 0x6f, 0x43, 0xc3, 0x8c,
	0x76, 0xb6, 0x4c, 0x74, 0xe4, 0x04, 0xe7, 0x00, 0x3a, 0x61, 0x82, 0x62, 0x3f, 0xa1, 0x34, 0xf2,
	0xc9, 0x24, 0xe6, 0xdd, 0x9a, 0xb2, 0xd1, 0x83, 0x82, 0xd7, 0x16, 0x25, 0x5e, 0xdf, 0x49, 0x50,
	0x2c, 0xbd, 0x78, 0x6f, 0x12, 0x1b, 0xb0, 0x68, 0x85, 0x16, 0x49, 0xa6, 0xb5, 0x3c, 0xeb, 0x29,
	0x84, 0x94, 0xe2, 0x36, 0xb3, 0xbc, 0x87, 0xb9, 0x0c, 0x77, 0xe5, 0xb3, 0x3b, 0x5b, 0xc6, 0x86,
	0xe9, 0x30, 0xb3, 0x0c, 0xe4, 0x96, 0x91, 0xa8, 0x7b, 0x44, 0xb9, 0xf0, 0x13, 0xca, 0x84, 0x1f,
	0xa1, 0x21, 0x8e, 0xba, 0x4d, 0x35, 0xdd, 0x96, 0xe4, 0x7d, 0xca, 0xc4, 0xae, 0x24, 0x4a, 0xf5,
	0x4c, 0x49, 0xd8, 0x6d, 0xe9, 0x90, 0x99, 0x92, 0xd0, 0x59, 0x81, 0x3a, 0x21, 0x54, 0xe7, 0xb5,
	0xb6, 0xc1, 0x15, 0x42, 0x65, 0x62, 0xeb, 0x7d, 0x02, 0x37, 0x2e, 0x5c, 0xe4, 0x3a, 0x60, 0x6b,
	0xdb, 0xc0, 0xf6, 0x59, 0x13, 0x1a, 0x79, 0xc1, 0x50, 0x66, 0xc6, 0x7b, 0xb0, 0x30, 0x3c, 0x4b,
	0x10, 0xe7, 0x3e, 0xd3, 0x8e, 0xc5, 0x4c, 0x6a, 0xeb, 0x68, 0xb2, 0x71, 0x37, 0x26, 0xdd, 0x3d,
	0x1c, 0x6b, 0xb7, 0xd1, 0xe8, 0x57, 0x0b, 0xc7, 0xd2, 0x61, 0xae, 0x37, 0xaf, 0x41, 0x89, 0xb9,
	0x1c, 0x25, 0xac, 0xd0, 0xa9, 0x15, 0x42, 0xe7, 0x15, 0xcc, 0xf2, 0x1e, 0x2c, 0x58, 0xee, 0x80,
	0x62, 0xcc, 0xbb, 0x0d, 0xc5, 0xd5, 0xce, 0x0c, 0x2c, 0x89, 0x72, 0x2b, 0x14, 0xc8, 0x38, 0x34,
	0x5e, 0xaa, 0x8d, 0xd5, 0x54, 0x34, 0xe3, 0xd6, 0x9b, 0xd0, 0xd4, 0x60, 0xa5, 0x13, 0x5d, 0x53,
	0x81, 0xe1, 0x5a, 0xa9, 0x5b, 0xad, 0x0f, 0x70, 0xbc, 0xb3, 0xad, 0x71, 0x00, 0xd4, 0x22, 0x9d,
	0xf8, 0x3e, 0x82, 0x86, 0x40, 0x89, 0xd9, 0xa0, 0xa5, 0x36, 0xb8, 0x53, 0xbe, 0xc1, 0x73, 0x94,
	0xe8, 0xe5, 0x75, 0x61, 0xbe, 0x64, 0x08, 0x29, 0x4f, 0xe1, 0xdd, 0xb6, 0xba, 0x81, 0x19, 0x49,
	0x7a, 0x82, 0x18, 0x26, 0xa2, 0xdb, 0xd1, 0xda, 0xd1, 0xa3, 0x32, 0x1f, 0x5b, 0x28, 0xf3, 0xb1,
	0x3e, 0x54, 0xc7, 0x27, 0x41, 0x77, 0xf1, 0xaa, 0xfb, 0x6c, 0xeb, 0x62, 0x23, 0x24, 0x87, 0x9e,
	0x64, 0x76, 0x06, 0xb0, 0x10, 0x85, 0x64, 0x72, 0xaa, 0x55, 0x9a, 0xc8, 0x0a, 0xee, 0x86, 0x5a,
	0x7f, 0xb7, 0x7c, 0xfd, 0xae, 0x64, 0xde, 0x4b, 0x79, 0xbd, 0x4e, 0x54, 0x18, 0x3b, 0x3f, 0x84,
	0x65, 0x76, 0xea, 0x27, 0x11, 0x1a, 0xe1, 0x58, 0xc2, 0x0d, 0xc7, 0x42, 0x84, 0xe4, 0x90, 0x77,
	0x1d, 0xb5, 0xe9, 0xfb, 0xe5, 0x9b, 0x7a, 0xa7, 0xfb, 0xe9, 0x8a, 0x03, 0xb3, 0xc0, 0x5b, 0x62,
	0x17, 0x89, 0xbd, 0xbf, 0x55, 0x00, 0x72, 0x8b, 0x48, 0xc7, 0x56, 0xce, 0x64, 0x1c, 0x5b, 0x7e,
	0xbf, 0x7a, 0x26, 0x92, 0x40, 0x86, 0x47, 0x0c, 0x8b, 0xd4, 0xaf, 0xf5, 0x48, 0xe6, 0x6c, 0x26,
	0x2b, 0x4a, 0x1e, 0xbe, 0xc4, 0xc6, 0xab, 0xeb, 0x92, 0x70, 0x10, 0xbe, 0x54, 0x4e, 0x3f, 0x9c,
	0x8c, 0xc7, 0x98, 0xe9, 0x69, 0x5d, 0xa3, 0x83, 0x26, 0x29, 0x06, 0xb9, 0xfa, 0xd4, 0xff, 0xd1,
	0x04, 0x4f, 0x30, 0x37, 0x4e, 0x5e, 0x67, 0xa7, 0xdf, 0x56, 0x63, 0x39, 0x29, 0xb2, 0x49, 0x9d,
	0x3c, 0xea, 0xc2, 0x4c, 0xf6, 0x22, 0xa8, 0xa7, 0xbe, 0x22, 0x91, 0x31, 0xb7, 0x87, 0xa9, 0xcd,
	0x33, 0x82, 0xb3, 0x06, 0x2d, 0x76, 0xea, 0xe7, 0x42, 0xea, 0xfb, 0x01, 0x3b, 0xf5, 0x52, 0x31,
	0xd7, 0xa0, 0x25, 0x6c, 0x0e, 0x53, 0x1a, 0x8b, 0x8c, 0xa3, 0xf7, 0x9b, 0x0a, 0x40, 0xee, 0x0b,
	0xce, 0x06, 0xb4, 0xa2, 0x87, 0x2a, 0x75, 0xa9, 0x7c, 0x6a, 0x6a, 0xb2, 0x9b, 0xb6, 0xb9, 0xf2,
	0x6e, 0xc9, 0x83, 0xe8, 0xe1, 0x0b, 0x36, 0xd6, 0x9d, 0xd3, 0x03, 0xa8, 0x45, 0x0f, 0x7d, 0xc4,
	0x92, 0xee, 0x4c, 0xd9, 0x9a, 0xb4, 0xdf, 0xf0, 0xe6, 0x22, 0xf9, 0xad, 0xd8, 0xfb, 0xfe, 0x38,
	0x1c, 0xaa, 0x4c, 0x71, 0x9e, 0x3d, 0x6b, 0x0f, 0xbc, 0xb9, 0xa8, 0xbf, 0x1d, 0x0e, 0x7b, 0x3f,
	0xaf, 0x40, 0xa7, 0xe8, 0x72, 0xd2, 0xe8, 0x0a, 0x8d, 0x8c, 0xd1, 0xe5, 0xb7, 0xca, 0xa2, 0x61,
	0x60, 0x70, 0x50, 0x7e, 0x3a, 0x2e, 0xb4, 0xe2, 0x70, 0xc4, 0x28, 0xc7, 0x6c, 0x1a, 0x66, 0x6d,
	0x49, 0x81, 0x96, 0xe1, 0xe2, 0xac, 0x85, 0x8b, 0x3d, 0xa8, 0x8f, 0xc3, 0x08, 0x27, 0x48, 0x1c,
	0x19, 0xeb, 0x66, 0xe3, 0xde, 0x0f, 0x60, 0xa9, 0xc4, 0x53, 0x25, 0x0c, 0x2b, 0x93, 0xa6, 0xad,
	0xa3, 0x1a, 0xa8, 0x2e, 0x8d, 0xb2, 0x63, 0x83, 0xab, 0xb2, 0x4b, 0x53, 0x23, 0x85, 0xa7, 0xdc,
	0x8f, 0x51, 0x48, 0x4c, 0x97, 0x50, 0x0b, 0xf9, 0x00, 0x85, 0xc4, 0x95, 0x57, 0xcd, 0x2b, 0x04,
	0x55, 0x8f, 0xae, 0x40, 0x3d, 0xa1, 0x81, 0x9d, 0xb3, 0xe7, 0x13, 0x1a, 0x28, 0xf4, 0xfd, 0x10,
	0x20, 0xeb, 0xb9, 0xb8, 0xd1, 0xe5, 0x72, 0x69, 0x74, 0x79, 0x16, 0xa3, 0xf3, 0x1e, 0xcc, 0xc9,
	0x6a, 0x46, 0xc2, 0xb5, 0x5c, 0xb1, 0x58, 0xd4, 0xfe, 0xd3, 0x2d, 0x4f, 0x4f, 0xbb, 0x0c, 0x20,
	0x97, 0xe5, 0x0d, 0x8b, 0xd3, 0xf5, 0x42, 0x71, 0x5a, 0x28, 0x36, 0x8b, 0xf7, 0xd4, 0xe5, 0xa9,
	0xfb, 0xef, 0x19, 0x80, 0xaf, 0x53, 0x42, 0xb0, 0x6e, 0xd2, 0xca, 0xb2, 0xd6, 0x2a, 0x34, 0x46,
	0x94, 0x10, 0x5b, 0x23, 0x75, 0x49, 0x50, 0x2a, 0x79, 0x04, 0x2b, 0xa6, 0x30, 0xf7, 0x65, 0x6a,
	0xf6, 0xe9, 0x14, 0xb3, 0x08, 0x9d, 0xe9, 0x0c, 0xab, 0xed, 0x7f, 0xd3, 0x30, 0xc8, 0xea, 0xeb,
	0x5b, 0x7a, 0x5a, 0x75, 0x92, 0xff, 0x0f, 0x1d, 0xa9, 0x68, 0x4b, 0xa3, 0xb3, 0x3a, 0xb7, 0x24,
	0x34, 0xd8, 0xc9, 0xb5, 0x77, 0x0f, 0x16, 0xd4, 0xce, 0x16, 0xdf, 0x9c, 0xe2, 0xeb, 0x48, 0xb2,
	0xc5, 0xd8, 0x87, 0xe5, 0x22, 0xa3, 0x6f, 0x00, 0xbf, 0xa6, 0xd8, 0x97, 0x0a, 0xec, 0xbb, 0x1a,
	0xfd, 0x5d, 0x68, 0x4f, 0x38, 0xd6, 0xa2, 0x4b, 0x23, 0x18, 0x80, 0x68, 0x4e, 0x38, 0x96, 0xe2,
	0xee, 0xf6, 0x87, 0x81, 0x73, 0x17, 0x66, 0xd5, 0x54, 0x5d, 0xa9, 0xf4, 0xa2, 0xf5, 0xd4, 0xac,
	0xf5, 0x98, 0xd1, 0xb0, 0x1f, 0x33, 0xde, 0x81, 0xa6, 0x52, 0x5e, 0x8c, 0xc5, 0x11, 0x0d, 0x4c,
	0x62, 0x04, 0x49, 0x1a, 0x28, 0x8a, 0xfb, 0x8f, 0x2a, 0xbc, 0x65, 0x2c, 0x73, 0xa0, 0x43, 0xc4,
	0x24, 0x4c, 0xd9, 0x68, 0x27, 0x12, 0xf3, 0xec, 0xc2, 0x0f, 0x24, 0xe9, 0xe0, 0xb2, 0xe2, 0xef,
	0x25, 0xf4, 0x4c, 0x61, 0x11, 0xf8, 0x79, 0xf5, 0x89, 0x89, 0x60, 0x21, 0x4e, 0xbd, 0xef, 0xe3,
	0x12, 0x97, 0x28, 0x1c, 0xbc, 0x5e, 0x56, 0xf4, 0x86, 0x69, 0x1b, 0x78, 0x8b, 0x95, 0xcf, 0x3a,
	0xfb, 0x85, 0xd8, 0xd0, 0x95, 0xfd, 0x97, 0xaf, 0x3d, 0x2b, 0x37, 0x9f, 0xde, 0xde, 0xda, 0xa3,
	0x17, 0xc3, 0xed, 0xab, 0x44, 0x29, 0xa9, 0xcd, 0xbe, 0x66, 0xd7, 0x66, 0xcd, 0xfe, 0xbb, 0xf6,
	0xf1, 0xa5, 0xa5, 0xbc, 0x55, 0xbe, 0xf5, 0xbe, 0x67, 0x95, 0xe2, 0x97, 0x9e, 0xf0, 0x41, 0xf1,
	0x84, 0xd5, 0x2b, 0xca, 0x62, 0xbb, 0x34, 0xfc, 0x59, 0x05, 0x9c, 0x73, 0xf7, 0x97, 0x50, 0xf3,
	0x08, 0x5a, 0x69, 0xf0, 0x24, 0x34, 0xe0, 0x65, 0xe8, 0x9c, 0x07, 0xad, 0xd7, 0x24, 0xd9, 0x37,
	0x77, 0x36, 0xb4, 0x5f, 0xe9, 0xb0, 0x4d, 0x6d, 0x5b, 0x58, 0x99, 0x47, 0xb5, 0x67, 0xb3, 0xba,
	0xbf, 0xcf, 0x21, 0xcf, 0xc8, 0xf2, 0x86, 0x50, 0xd3, 0x2f, 0x40, 0xcd, 0x9d, 0x2b, 0x6c, 0x9d,
	0x77, 0xc3, 0x1b, 0xe7, 0xba, 0xe1, 0xb5, 0xeb, 0x3c, 0x24, 0xeb, 0x89, 0x7f, 0x37, 0x03, 0xdd,
	0xbd, 0x0b, 0x40, 0x62, 0x42, 0x21, 0xef, 0x8f, 0x2a, 0x65, 0xfd, 0xd1, 0x4c, 0x1e, 0x22, 0x3f,
	0xbd, 0x32, 0x44, 0xb4, 0x01, 0x36, 0x4b, 0x84, 0xba, 0x70, 0xe6, 0x9b, 0x85, 0xc9, 0xff, 0xd8,
	0xa9, 0xdd, 0xbf, 0xcf, 0xc3, 0xcd, 0x92, 0x1b, 0x48, 0x53, 0x7c, 0x01, 0x6e, 0x98, 0x9c, 0xec,
	0xc7, 0x98, 0x1f, 0xf9, 0x56, 0x7e, 0x5f, 0x30, 0x13, 0x03, 0xcc, 0x8f, 0x14, 0xca, 0xdf, 0x83,
	0x85, 0xdc, 0x85, 0xec, 0x44, 0xd0, 0xc9, 0xc9, 0x8a, 0x91, 0xc1, 0xca, 0xf4, 0x34, 0x42, 0xc4,
	0x3f, 0x9a, 0x0c, 0x7d, 0x44, 0x02, 0x9f, 0x27, 0xf4, 0x18, 0x9b, 0x92, 0x5d, 0x9b, 0x7c, 0xe3,
	0x1a, 0xed, 0x26, 0x78, 0xb4, 0xfe, 0x42, 0xee, 0xf1, 0xe9, 0x64, 0xb8, 0x49, 0x82, 0x03, 0xb9,
	0x81, 0x2e, 0xe6, 0x97, 0xa7, 0x65, 0x64, 0xe7, 0xfb, 0xb0, 0xa8, 0xcf, 0x54, 0xd7, 0xd0, 0x47,
	0xcd, 0xaa, 0xa3, 0x3e, 0x78, 0xd5, 0xa3, 0xe4, 0x45, 0xf5, 0x19, 0x9d, 0x69, 0x61, 0xdc, 0xfb,
	0xe3, 0x0c, 0x2c, 0x97, 0x4a, 0x23, 0x53, 0x87, 0xbc, 0xa4, 0x4a, 0x1d, 0x56, 0xce, 0x6c, 0x1e,
	0x4d, 0x86, 0xf2, 0x0c, 0x95, 0xe2, 0x4c, 0x03, 0x3a, 0x93, 0x37, 0xa0, 0x1f, 0xc2, 0xad, 0x88,
	0xd2, 0x64, 0x88, 0x46, 0xc7, 0x7e, 0xb1, 0xb5, 0x32, 0xd9, 0xf2, 0xad, 0x74, 0x7a, 0xc7, 0xea,
	0xb0, 0x9c, 0xc7, 0xb0, 0x32, 0x62, 0x18, 0x09, 0xec, 0xe7, 0xab, 0xb3, 0xd7, 0x5f, 0xfd, 0xa4,
	0x79, 0x4b, 0x33, 0xec, 0xa6, 0xcb, 0xb3, 0x4e, 0x74, 0x13, 0xde, 0x3e, 0xbf, 0xd6, 0x7e, 0xc6,
	0xe1, 0xe6, 0xe9, 0xb3, 0x57, 0x5c, 0x6f, 0xbd, 0xe1, 0x70, 0xe7, 0x13, 0xb8, 0x5d, 0xc8, 0xf2,
	0xe7, 0x52, 0xac, 0xa9, 0xb9, 0x57, 0xac, 0x44, 0x5f, 0x4c, 0xb4, 0xbd, 0xbf, 0xce, 0x40, 0xa7,
	0xa8, 0x69, 0xd9, 0x60, 0x4d, 0x49, 0xa8, 0x9f, 0xe9, 0x7c, 0xf5, 0x7c, 0x67, 0x6a, 0xb9, 0xf6,
	0x94, 0x84, 0xea, 0xb1, 0xee, 0x40, 0x12, 0xd5, 0x6b, 0x4b, 0xc6, 0x87, 0x49, 0x5a, 0x70, 0x36,
	0x53, 0xae, 0x67, 0x24, 0xf8, 0x9c, 0x6a, 0xd5, 0xfd, 0x43, 0x9e, 0x56, 0x2c, 0xb7, 0x7e, 0x43,
	0x38, 0xff, 0x6a, 0x01, 0xce, 0xdd, 0xeb, 0x43, 0xc7, 0x40, 0xfa, 0x93, 0x73, 0x90, 0x7e, 0xf7,
	0x55, 0xd0, 0x33, 0x83, 0xf5, 0xcf, 0x2a, 0xb0, 0x60, 0x31, 0x29, 0x64, 0x72, 0xa1, 0x7d, 0xbc,
	0xc1, 0x2f, 0x46, 0xd6, 0xf1, 0x06, 0xcf, 0x22, 0x6b, 0x15, 0x1a, 0x6a, 0xde, 0x2e, 0x4a, 0x25,
	0xa1, 0xa4, 0x4e, 0x9f, 0x7d, 0xed, 0x3a, 0x7d, 0xee, 0xea, 0x3a, 0xfd, 0x2f, 0x55, 0xb8, 0x61,
	0xcb, 0xfc, 0xba, 0x39, 0xe8, 0xe4, 0x15, 0x72, 0xd0, 0xe3, 0x4b, 0xb4, 0xf8, 0x5f, 0xd5, 0x68,
	0x83, 0x92, 0x1a, 0xed, 0xc1, 0xd5, 0x07, 0x7d, 0x4e, 0x0a, 0xb4, 0xdf, 0x56, 0xa0, 0x69, 0x5d,
	0xfe, 0x0d, 0x43, 0xe8, 0x4b, 0x85, 0x10, 0x5a, 0xbd, 0x4c, 0xb3, 0x79, 0xec, 0x7c, 0x78, 0x2e,
	0x76, 0xde, 0xbe, 0xd2, 0x18, 0x59, 0xd0, 0xfc, 0xaa, 0x02, 0x2d, 0x5b, 0x84, 0xd2, 0xb6, 0xed,
	0x49, 0xf6, 0xe0, 0xa5, 0xdf, 0x08, 0xee, 0x5e, 0x76, 0x81, 0x75, 0xdd, 0x0b, 0x69, 0x7d, 0x9b,
	0x35, 0xbd, 0x47, 0xd0, 0xb4, 0xc8, 0xaf, 0xf3, 0x83, 0x67, 0x58, 0x53, 0x3f, 0x7e, 0x1f, 0xfe,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x3c, 0x62, 0x65, 0x0c, 0x1e, 0x00, 0x00,
}
