// +build !ignore_autogenerated

// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by deepcopy-gen. DO NOT EDIT.

package controller

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BDParms) DeepCopyInto(out *BDParms) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BDParms.
func (in *BDParms) DeepCopy() *BDParms {
	if in == nil {
		return nil
	}
	out := new(BDParms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	if in.PodInterfaces != nil {
		in, out := &in.PodInterfaces, &out.PodInterfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeInterfaces != nil {
		in, out := &in.NodeInterfaces, &out.NodeInterfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeInterfaceLabels != nil {
		in, out := &in.NodeInterfaceLabels, &out.NodeInterfaceLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.L2Bd != nil {
		in, out := &in.L2Bd, &out.L2Bd
		*out = new(L2BD)
		(*in).DeepCopyInto(*out)
	}
	if in.L3Routes != nil {
		in, out := &in.L3Routes, &out.L3Routes
		*out = make([]*L3VRFRoute, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = (*in).DeepCopy()
			}
		}
	}
	if in.L3Arps != nil {
		in, out := &in.L3Arps, &out.L3Arps
		*out = make([]*L3ArpEntry, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(L3ArpEntry)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.L2Fibs != nil {
		in, out := &in.L2Fibs, &out.L2Fibs
		*out = make([]*L2FIBEntry, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(L2FIBEntry)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAMPool) DeepCopyInto(out *IPAMPool) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(MetaDataType)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(IPAMPoolSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(IPAMPoolStatus)
		(*in).DeepCopyInto(*out)
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAMPool.
func (in *IPAMPool) DeepCopy() *IPAMPool {
	if in == nil {
		return nil
	}
	out := new(IPAMPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAMPoolSpec) DeepCopyInto(out *IPAMPoolSpec) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAMPoolSpec.
func (in *IPAMPoolSpec) DeepCopy() *IPAMPoolSpec {
	if in == nil {
		return nil
	}
	out := new(IPAMPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAMPoolStatus) DeepCopyInto(out *IPAMPoolStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAMPoolStatus.
func (in *IPAMPoolStatus) DeepCopy() *IPAMPoolStatus {
	if in == nil {
		return nil
	}
	out := new(IPAMPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSecTunnel) DeepCopyInto(out *IPSecTunnel) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSecTunnel.
func (in *IPSecTunnel) DeepCopy() *IPSecTunnel {
	if in == nil {
		return nil
	}
	out := new(IPSecTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interface) DeepCopyInto(out *Interface) {
	*out = *in
	if in.IpAddresses != nil {
		in, out := &in.IpAddresses, &out.IpAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IpamPoolNames != nil {
		in, out := &in.IpamPoolNames, &out.IpamPoolNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MemifParms != nil {
		in, out := &in.MemifParms, &out.MemifParms
		*out = new(Interface_MemIFParms)
		(*in).DeepCopyInto(*out)
	}
	if in.TapParms != nil {
		in, out := &in.TapParms, &out.TapParms
		*out = new(Interface_TapParms)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Fwd != nil {
		in, out := &in.Fwd, &out.Fwd
		*out = new(Interface_Forwarding)
		(*in).DeepCopyInto(*out)
	}
	if in.RxPlacementSettings != nil {
		in, out := &in.RxPlacementSettings, &out.RxPlacementSettings
		*out = new(Interface_RxPlacementSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.IpsecTunnels != nil {
		in, out := &in.IpsecTunnels, &out.IpsecTunnels
		*out = make([]*IPSecTunnel, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IPSecTunnel)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interface.
func (in *Interface) DeepCopy() *Interface {
	if in == nil {
		return nil
	}
	out := new(Interface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceStatus) DeepCopyInto(out *InterfaceStatus) {
	*out = *in
	if in.Msg != nil {
		in, out := &in.Msg, &out.Msg
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IpamPoolNums != nil {
		in, out := &in.IpamPoolNums, &out.IpamPoolNums
		*out = make(map[string]uint32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IpAddresses != nil {
		in, out := &in.IpAddresses, &out.IpAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceStatus.
func (in *InterfaceStatus) DeepCopy() *InterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(InterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interface_Forwarding) DeepCopyInto(out *Interface_Forwarding) {
	*out = *in
	if in.L3Route != nil {
		in, out := &in.L3Route, &out.L3Route
		*out = make([]*L3VRFRoute, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = (*in).DeepCopy()
			}
		}
	}
	if in.L3Arp != nil {
		in, out := &in.L3Arp, &out.L3Arp
		*out = make([]*L3ArpEntry, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(L3ArpEntry)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.L2Fib != nil {
		in, out := &in.L2Fib, &out.L2Fib
		*out = make([]*L2FIBEntry, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(L2FIBEntry)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interface_Forwarding.
func (in *Interface_Forwarding) DeepCopy() *Interface_Forwarding {
	if in == nil {
		return nil
	}
	out := new(Interface_Forwarding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interface_MemIFParms) DeepCopyInto(out *Interface_MemIFParms) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interface_MemIFParms.
func (in *Interface_MemIFParms) DeepCopy() *Interface_MemIFParms {
	if in == nil {
		return nil
	}
	out := new(Interface_MemIFParms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interface_RxPlacementSettings) DeepCopyInto(out *Interface_RxPlacementSettings) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interface_RxPlacementSettings.
func (in *Interface_RxPlacementSettings) DeepCopy() *Interface_RxPlacementSettings {
	if in == nil {
		return nil
	}
	out := new(Interface_RxPlacementSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interface_TapParms) DeepCopyInto(out *Interface_TapParms) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interface_TapParms.
func (in *Interface_TapParms) DeepCopy() *Interface_TapParms {
	if in == nil {
		return nil
	}
	out := new(Interface_TapParms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2BD) DeepCopyInto(out *L2BD) {
	*out = *in
	if in.BdParms != nil {
		in, out := &in.BdParms, &out.BdParms
		*out = new(BDParms)
		(*in).DeepCopyInto(*out)
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2BD.
func (in *L2BD) DeepCopy() *L2BD {
	if in == nil {
		return nil
	}
	out := new(L2BD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2FIBEntry) DeepCopyInto(out *L2FIBEntry) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2FIBEntry.
func (in *L2FIBEntry) DeepCopy() *L2FIBEntry {
	if in == nil {
		return nil
	}
	out := new(L2FIBEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ArpEntry) DeepCopyInto(out *L3ArpEntry) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ArpEntry.
func (in *L3ArpEntry) DeepCopy() *L3ArpEntry {
	if in == nil {
		return nil
	}
	out := new(L3ArpEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3VRFRoute.
func (in *L3VRFRoute) DeepCopy() *L3VRFRoute {
	if in == nil {
		return nil
	}
	out := new(L3VRFRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetaDataType) DeepCopyInto(out *MetaDataType) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaDataType.
func (in *MetaDataType) DeepCopy() *MetaDataType {
	if in == nil {
		return nil
	}
	out := new(MetaDataType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNode) DeepCopyInto(out *NetworkNode) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(MetaDataType)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(NetworkNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(NetworkNodeStatus)
		(*in).DeepCopyInto(*out)
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNode.
func (in *NetworkNode) DeepCopy() *NetworkNode {
	if in == nil {
		return nil
	}
	out := new(NetworkNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNodeOverlay) DeepCopyInto(out *NetworkNodeOverlay) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(MetaDataType)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(NetworkNodeOverlaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(NetworkNodeOverlayStatus)
		(*in).DeepCopyInto(*out)
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNodeOverlay.
func (in *NetworkNodeOverlay) DeepCopy() *NetworkNodeOverlay {
	if in == nil {
		return nil
	}
	out := new(NetworkNodeOverlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNodeOverlaySpec) DeepCopyInto(out *NetworkNodeOverlaySpec) {
	*out = *in
	if in.VxlanHubAndSpokeParms != nil {
		in, out := &in.VxlanHubAndSpokeParms, &out.VxlanHubAndSpokeParms
		*out = new(NetworkNodeOverlaySpec_VxlanHubAndSpokeParms)
		(*in).DeepCopyInto(*out)
	}
	if in.VxlanMeshParms != nil {
		in, out := &in.VxlanMeshParms, &out.VxlanMeshParms
		*out = new(NetworkNodeOverlaySpec_VxlanMeshParms)
		(*in).DeepCopyInto(*out)
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNodeOverlaySpec.
func (in *NetworkNodeOverlaySpec) DeepCopy() *NetworkNodeOverlaySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkNodeOverlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) DeepCopyInto(out *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNodeOverlaySpec_VxlanHubAndSpokeParms.
func (in *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms) DeepCopy() *NetworkNodeOverlaySpec_VxlanHubAndSpokeParms {
	if in == nil {
		return nil
	}
	out := new(NetworkNodeOverlaySpec_VxlanHubAndSpokeParms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNodeOverlaySpec_VxlanMeshParms) DeepCopyInto(out *NetworkNodeOverlaySpec_VxlanMeshParms) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNodeOverlaySpec_VxlanMeshParms.
func (in *NetworkNodeOverlaySpec_VxlanMeshParms) DeepCopy() *NetworkNodeOverlaySpec_VxlanMeshParms {
	if in == nil {
		return nil
	}
	out := new(NetworkNodeOverlaySpec_VxlanMeshParms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNodeOverlayStatus) DeepCopyInto(out *NetworkNodeOverlayStatus) {
	*out = *in
	if in.Msg != nil {
		in, out := &in.Msg, &out.Msg
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RenderedVppAgentEntries != nil {
		in, out := &in.RenderedVppAgentEntries, &out.RenderedVppAgentEntries
		*out = make(map[string]*RenderedVppAgentEntry, len(*in))
		for key, val := range *in {
			var outVal *RenderedVppAgentEntry
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(RenderedVppAgentEntry)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNodeOverlayStatus.
func (in *NetworkNodeOverlayStatus) DeepCopy() *NetworkNodeOverlayStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkNodeOverlayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNodeSpec) DeepCopyInto(out *NetworkNodeSpec) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*Interface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Interface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.L2Bds != nil {
		in, out := &in.L2Bds, &out.L2Bds
		*out = make([]*L2BD, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(L2BD)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNodeSpec.
func (in *NetworkNodeSpec) DeepCopy() *NetworkNodeSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkNodeStatus) DeepCopyInto(out *NetworkNodeStatus) {
	*out = *in
	if in.Msg != nil {
		in, out := &in.Msg, &out.Msg
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RenderedVppAgentEntries != nil {
		in, out := &in.RenderedVppAgentEntries, &out.RenderedVppAgentEntries
		*out = make(map[string]*RenderedVppAgentEntry, len(*in))
		for key, val := range *in {
			var outVal *RenderedVppAgentEntry
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(RenderedVppAgentEntry)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make(map[string]*InterfaceStatus, len(*in))
		for key, val := range *in {
			var outVal *InterfaceStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(InterfaceStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkNodeStatus.
func (in *NetworkNodeStatus) DeepCopy() *NetworkNodeStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPod) DeepCopyInto(out *NetworkPod) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(MetaDataType)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(NetworkPodSpec)
		(*in).DeepCopyInto(*out)
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPod.
func (in *NetworkPod) DeepCopy() *NetworkPod {
	if in == nil {
		return nil
	}
	out := new(NetworkPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPodSpec) DeepCopyInto(out *NetworkPodSpec) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*Interface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Interface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.L2Bds != nil {
		in, out := &in.L2Bds, &out.L2Bds
		*out = make([]*L2BD, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(L2BD)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPodSpec.
func (in *NetworkPodSpec) DeepCopy() *NetworkPodSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPodToNodeMap) DeepCopyInto(out *NetworkPodToNodeMap) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPodToNodeMap.
func (in *NetworkPodToNodeMap) DeepCopy() *NetworkPodToNodeMap {
	if in == nil {
		return nil
	}
	out := new(NetworkPodToNodeMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkService) DeepCopyInto(out *NetworkService) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(MetaDataType)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(NetworkServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(NetworkServiceStatus)
		(*in).DeepCopyInto(*out)
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkService.
func (in *NetworkService) DeepCopy() *NetworkService {
	if in == nil {
		return nil
	}
	out := new(NetworkService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkServiceSpec) DeepCopyInto(out *NetworkServiceSpec) {
	*out = *in
	if in.NetworkPods != nil {
		in, out := &in.NetworkPods, &out.NetworkPods
		*out = make([]*NetworkPod, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkPod)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]*Connection, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Connection)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkServiceSpec.
func (in *NetworkServiceSpec) DeepCopy() *NetworkServiceSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkServiceStatus) DeepCopyInto(out *NetworkServiceStatus) {
	*out = *in
	if in.Msg != nil {
		in, out := &in.Msg, &out.Msg
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RenderedVppAgentEntries != nil {
		in, out := &in.RenderedVppAgentEntries, &out.RenderedVppAgentEntries
		*out = make(map[string]*RenderedVppAgentEntry, len(*in))
		for key, val := range *in {
			var outVal *RenderedVppAgentEntry
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(RenderedVppAgentEntry)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make(map[string]*InterfaceStatus, len(*in))
		for key, val := range *in {
			var outVal *InterfaceStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(InterfaceStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkServiceStatus.
func (in *NetworkServiceStatus) DeepCopy() *NetworkServiceStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderedVppAgentEntry) DeepCopyInto(out *RenderedVppAgentEntry) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderedVppAgentEntry.
func (in *RenderedVppAgentEntry) DeepCopy() *RenderedVppAgentEntry {
	if in == nil {
		return nil
	}
	out := new(RenderedVppAgentEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemParameters) DeepCopyInto(out *SystemParameters) {
	*out = *in
	if in.L2BdTemplates != nil {
		in, out := &in.L2BdTemplates, &out.L2BdTemplates
		*out = make([]*BDParms, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(BDParms)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemParameters.
func (in *SystemParameters) DeepCopy() *SystemParameters {
	if in == nil {
		return nil
	}
	out := new(SystemParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPPRoute) DeepCopyInto(out *VPPRoute) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPPRoute.
func (in *VPPRoute) DeepCopy() *VPPRoute {
	if in == nil {
		return nil
	}
	out := new(VPPRoute)
	in.DeepCopyInto(out)
	return out
}
