---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sfc-controller-cfg
data:
  etcd.conf: |
    insecure-transport: true
    dial-timeout: 1000000000
    endpoints:
     - "172.17.0.1:22379"
  kafka.conf: |
    addrs:
     - "172.17.0.1:9092"
---
apiVersion: v1
kind: Pod
metadata:
  name: vnf
spec:
  containers:
    - name: "sfc-controller"
      image: dev_sfc_controller
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      volumeMounts:
        - name: agent-config
          mountPath: /opt/sfc-controller/dev
  volumes:
  - name: controller-config
    configMap:
      name: sfc-controller-cfg
