// Code generated by protoc-gen-gogo.
// source: l2.proto
// DO NOT EDIT!

/*
Package l2 is a generated protocol buffer package.

It is generated from these files:
	l2.proto

It has these top-level messages:
	HEIDs
	HE2EEIDs
	HE2HEIDs
	SFCIDs
*/
package l2

import proto "github.com/gogo/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type HEIDs struct {
	Name              string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LoopbackMacAddrId uint32 `protobuf:"varint,2,opt,name=loopback_mac_addr_id,proto3" json:"loopback_mac_addr_id,omitempty"`
}

func (m *HEIDs) Reset()         { *m = HEIDs{} }
func (m *HEIDs) String() string { return proto.CompactTextString(m) }
func (*HEIDs) ProtoMessage()    {}

type HE2EEIDs struct {
	HeName string `protobuf:"bytes,1,opt,name=he_name,proto3" json:"he_name,omitempty"`
	EeName string `protobuf:"bytes,2,opt,name=ee_name,proto3" json:"ee_name,omitempty"`
	VlanId uint32 `protobuf:"varint,3,opt,name=vlan_id,proto3" json:"vlan_id,omitempty"`
}

func (m *HE2EEIDs) Reset()         { *m = HE2EEIDs{} }
func (m *HE2EEIDs) String() string { return proto.CompactTextString(m) }
func (*HE2EEIDs) ProtoMessage()    {}

type HE2HEIDs struct {
	ShName string `protobuf:"bytes,1,opt,name=sh_name,proto3" json:"sh_name,omitempty"`
	DhName string `protobuf:"bytes,2,opt,name=dh_name,proto3" json:"dh_name,omitempty"`
	VlanId uint32 `protobuf:"varint,3,opt,name=vlan_id,proto3" json:"vlan_id,omitempty"`
}

func (m *HE2HEIDs) Reset()         { *m = HE2HEIDs{} }
func (m *HE2HEIDs) String() string { return proto.CompactTextString(m) }
func (*HE2HEIDs) ProtoMessage()    {}

type SFCIDs struct {
	SfcName   string `protobuf:"bytes,1,opt,name=sfc_name,proto3" json:"sfc_name,omitempty"`
	Container string `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	Port      string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	IpId      uint32 `protobuf:"varint,4,opt,name=ip_id,proto3" json:"ip_id,omitempty"`
	MacAddrId uint32 `protobuf:"varint,5,opt,name=mac_addr_id,proto3" json:"mac_addr_id,omitempty"`
	MemifId   uint32 `protobuf:"varint,6,opt,name=memif_id,proto3" json:"memif_id,omitempty"`
	VethId    uint32 `protobuf:"varint,7,opt,name=veth_id,proto3" json:"veth_id,omitempty"`
}

func (m *SFCIDs) Reset()         { *m = SFCIDs{} }
func (m *SFCIDs) String() string { return proto.CompactTextString(m) }
func (*SFCIDs) ProtoMessage()    {}
